// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Related_notes.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zoho.OpenApiClient.Related_notes
{
    /// <summary>
    /// Builds and executes requests for operations under \related_notes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Related_notesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Zoho.OpenApiClient.related_notes.item collection</summary>
        /// <param name="position">The module API name of the parent record (e.g., Contacts, Leads, Deals, Accounts)</param>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Related_notes.Item.WithParentRecordModuleItemRequestBuilder"/></returns>
        public global::Soenneker.Zoho.OpenApiClient.Related_notes.Item.WithParentRecordModuleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("parentRecordModule", position);
                return new global::Soenneker.Zoho.OpenApiClient.Related_notes.Item.WithParentRecordModuleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Related_notes.Related_notesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Related_notesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/related_notes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Related_notes.Related_notesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Related_notesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/related_notes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
