// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values
{
    /// <summary>
    /// Builds and executes requests for operations under \pick_list_values\settings\fields\{fieldId}\actions\replace_pick_list_values
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Replace_pick_list_valuesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Replace_pick_list_valuesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pick_list_values/settings/fields/{fieldId}/actions/replace_pick_list_values?module={module}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Replace_pick_list_valuesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pick_list_values/settings/fields/{fieldId}/actions/replace_pick_list_values?module={module}", rawUrl)
        {
        }
        /// <summary>
        /// Replace picklist value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceResponse"/></returns>
        /// <param name="body">Container for the replace_pick_list_values array, listing one or more instructions to perform picklist value replacements.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Zoho.OpenApiClient.Models.PermissionDeniedErrorResponse">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceResponse?> PostAsync(global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceRequestBody body, Action<RequestConfiguration<global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder.Replace_pick_list_valuesRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceResponse> PostAsync(global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceRequestBody body, Action<RequestConfiguration<global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder.Replace_pick_list_valuesRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Soenneker.Zoho.OpenApiClient.Models.PermissionDeniedErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceResponse>(requestInfo, global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Replace picklist value
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Container for the replace_pick_list_values array, listing one or more instructions to perform picklist value replacements.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceRequestBody body, Action<RequestConfiguration<global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder.Replace_pick_list_valuesRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Zoho.OpenApiClient.Models.PicklistReplaceRequestBody body, Action<RequestConfiguration<global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder.Replace_pick_list_valuesRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zoho.OpenApiClient.Pick_list_values.Settings.Fields.Item.Actions.Replace_pick_list_values.Replace_pick_list_valuesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Replace picklist value
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Replace_pick_list_valuesRequestBuilderPostQueryParameters 
        {
            /// <summary>Specify the API name of the CRM module that contains the field. Refer to the [Get Modules](modules.json#$.paths./settings/modules.get) resource for valid values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("module")]
            public string? Module { get; set; }
#nullable restore
#else
            [QueryParameter("module")]
            public string Module { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
