// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Find_and_merge.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zoho.OpenApiClient.Find_and_merge.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \find_and_merge\{module}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithModuleItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Zoho.OpenApiClient.find_and_merge.item.item collection</summary>
        /// <param name="position">Unique identifier of the master record that will be retained after merge</param>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Find_and_merge.Item.Item.WithMasterRecordItemRequestBuilder"/></returns>
        public global::Soenneker.Zoho.OpenApiClient.Find_and_merge.Item.Item.WithMasterRecordItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("masterRecordId", position);
                return new global::Soenneker.Zoho.OpenApiClient.Find_and_merge.Item.Item.WithMasterRecordItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Find_and_merge.Item.WithModuleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithModuleItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/find_and_merge/{module}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Find_and_merge.Item.WithModuleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithModuleItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/find_and_merge/{module}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
