// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item.Map_dependency;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \map_dependency\settings\layouts\{layoutId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLayoutItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The map_dependency property</summary>
        public global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item.Map_dependency.Map_dependencyRequestBuilder Map_dependency
        {
            get => new global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item.Map_dependency.Map_dependencyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item.WithLayoutItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLayoutItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/map_dependency/settings/layouts/{layoutId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item.WithLayoutItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLayoutItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/map_dependency/settings/layouts/{layoutId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
