// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Models;
using Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type
{
    /// <summary>
    /// Builds and executes requests for operations under \portal_user_type\settings\portals\{portal}\user_type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class User_typeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Zoho.OpenApiClient.portal_user_type.settings.portals.item.user_type.item collection</summary>
        /// <param name="position">Unique id of the portal user type. Represented as a long numeric id encoded as a string.</param>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.Item.WithUserTypeItemRequestBuilder"/></returns>
        public global::Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.Item.WithUserTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userTypeId", position);
                return new global::Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.Item.WithUserTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.User_typeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public User_typeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/portal_user_type/settings/portals/{portal}/user_type", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.User_typeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public User_typeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/portal_user_type/settings/portals/{portal}/user_type", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve all user types for the specified portal.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeGetPortalUserTypes200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeGetPortalUserTypes200?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeGetPortalUserTypes200> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeGetPortalUserTypes200>(requestInfo, global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeGetPortalUserTypes200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create one or more portal user types for the specified portal. Request body must include a user_type array with one or more user type objects.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType200"/></returns>
        /// <param name="body">Request schema for creating portal user types.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType200?> PostAsync(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType200> PostAsync(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType200>(requestInfo, global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all user types for the specified portal.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create one or more portal user types for the specified portal. Request body must include a user_type array with one or more user type objects.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request schema for creating portal user types.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.User_typeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.User_typeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zoho.OpenApiClient.Portal_user_type.Settings.Portals.Item.User_type.User_typeRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
