// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>The permission level granted to the appointment owner for the associated record.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AppointmentPreferenceUpdateAppointmentPreferenceRequestAppointmentPreferencesSharingDetailsPermission
    {
        [EnumMember(Value = "read_only")]
        #pragma warning disable CS1591
        ReadOnlyValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "read_write")]
        #pragma warning disable CS1591
        ReadWrite,
        #pragma warning restore CS1591
        [EnumMember(Value = "full_access")]
        #pragma warning disable CS1591
        FullAccess,
        #pragma warning restore CS1591
    }
}
