// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the error message describing that the requested service status change is not allowed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AsServiceAvailabilityIsNotValidCommaStatusCannotBeChangedMessage
    {
        [EnumMember(Value = "As service availability is not valid, status cannot be changed")]
        #pragma warning disable CS1591
        AsServiceAvailabilityIsNotValidCommaStatusCannotBeChanged,
        #pragma warning restore CS1591
    }
}
