// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Filter criteria for an audit log export job.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuditLogCriterion : IAdditionalDataHolder, IComposedTypeWrapper, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterion"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterion? AuditLogGroupedCriterion { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterion AuditLogGroupedCriterion { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.AuditLogSimpleCriterion"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.AuditLogSimpleCriterion? AuditLogSimpleCriterion { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.AuditLogSimpleCriterion AuditLogSimpleCriterion { get; set; }
#endif
        /// <summary>Conditions to combine.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterionGroupItem>? Group { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterionGroupItem> Group { get; set; }
#endif
        /// <summary>Logical operator applied between the grouped conditions.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.AndGroupOperator? GroupOperator { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Models.AuditLogCriterion"/> and sets the default values.
        /// </summary>
        public AuditLogCriterion()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.AuditLogCriterion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.AuditLogCriterion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Zoho.OpenApiClient.Models.AuditLogCriterion();
            if("AuditLogGroupedCriterion".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AuditLogGroupedCriterion = new global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterion();
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.AndGroupOperator>() is global::Soenneker.Zoho.OpenApiClient.Models.AndGroupOperator groupOperatorValue)
            {
                result.GroupOperator = groupOperatorValue;
            }
            else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterionGroupItem>(global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterionGroupItem.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterionGroupItem> groupValue)
            {
                result.Group = groupValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AuditLogGroupedCriterion != null)
            {
                return AuditLogGroupedCriterion.GetFieldDeserializers();
            }
            else if(AuditLogSimpleCriterion != null)
            {
                return AuditLogSimpleCriterion.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AuditLogGroupedCriterion != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterion>(null, AuditLogGroupedCriterion);
            }
            else if(AuditLogSimpleCriterion != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.AuditLogSimpleCriterion>(null, AuditLogSimpleCriterion);
            }
            else if(GroupOperator != null)
            {
                writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.AndGroupOperator>(null, GroupOperator);
            }
            else if(Group != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.AuditLogGroupedCriterionGroupItem>(null, Group);
            }
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
