// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Identifies a related module whose open records&apos; ownership should be transferred alongside the parent record. Used by assign_owner actions, field_updates (Owner field), and convert actions (change_owner.related_modules). Common activity modules (Tasks, Calls, Events) are available for all modules and actions. Contacts is available for assign_owner when parent is Accounts, and for convert when converting Leads. Deals is available for assign_owner when parent is Accounts or Contacts, and for convert when converting Leads (requires create_deal=true).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomationRelatedRecord : IParsable
    {
        /// <summary>API name of the related module. Events, Calls, Tasks - open activity records, available for all modules and actions (assign_owner, convert). Contacts - available for assign_owner when parent is Accounts, and for convert when converting Leads. Deals - available for assign_owner when parent is Accounts or Contacts, and for convert when converting Leads (requires create_deal=true).</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.AutomationRelatedRecordApiName? ApiName { get; set; }
        /// <summary>Unique identifier of the related module. This is the module ID corresponding to the api_name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.AutomationRelatedRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.AutomationRelatedRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.AutomationRelatedRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_name", n => { ApiName = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.AutomationRelatedRecordApiName>(); } },
                { "id", n => { Id = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.AutomationRelatedRecordApiName>("api_name", ApiName);
            writer.WriteStringValue("id", Id);
        }
    }
}
#pragma warning restore CS0618
