// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>The group operator</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Bulk_read_createBulkReadJob_query_criteria_group_operator
    {
        [EnumMember(Value = "or")]
        #pragma warning disable CS1591
        Or,
        #pragma warning restore CS1591
        [EnumMember(Value = "and")]
        #pragma warning disable CS1591
        And,
        #pragma warning restore CS1591
    }
}
