// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// The criteria
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkReadCreateBulkReadJob_query_criteria : IParsable
    {
        /// <summary>The group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria_group>? Group { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria_group> Group { get; set; }
#endif
        /// <summary>The group operator</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria_group_operator? GroupOperator { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "group", n => { Group = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria_group>(global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria_group.CreateFromDiscriminatorValue)?.AsList(); } },
                { "group_operator", n => { GroupOperator = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria_group_operator>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria_group>("group", Group);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.BulkReadCreateBulkReadJob_query_criteria_group_operator>("group_operator", GroupOperator);
        }
    }
}
#pragma warning restore CS0618
