// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Operation details including affected record ID
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkOperationResponse_data_details : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>API name of the field that caused the error (if applicable).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiName { get; set; }
#nullable restore
#else
        public string ApiName { get; set; }
#endif
        /// <summary>ID of the affected record</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>JSONPath to the field in request payload (if applicable).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JsonPath { get; set; }
#nullable restore
#else
        public string JsonPath { get; set; }
#endif
        /// <summary>Parameter name that caused the error (if applicable).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParamName { get; set; }
#nullable restore
#else
        public string ParamName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Models.BulkOperationResponse_data_details"/> and sets the default values.
        /// </summary>
        public BulkOperationResponse_data_details()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.BulkOperationResponse_data_details"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.BulkOperationResponse_data_details CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.BulkOperationResponse_data_details();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_name", n => { ApiName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "json_path", n => { JsonPath = n.GetStringValue(); } },
                { "param_name", n => { ParamName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_name", ApiName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("json_path", JsonPath);
            writer.WriteStringValue("param_name", ParamName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
