// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>First day of the work week for the organization</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BusinessHoursUpdateBusinessHours_business_hours_week_starts_on
    {
        [EnumMember(Value = "Monday")]
        #pragma warning disable CS1591
        Monday,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tuesday")]
        #pragma warning disable CS1591
        Tuesday,
        #pragma warning restore CS1591
        [EnumMember(Value = "Wednesday")]
        #pragma warning disable CS1591
        Wednesday,
        #pragma warning restore CS1591
        [EnumMember(Value = "Thursday")]
        #pragma warning disable CS1591
        Thursday,
        #pragma warning restore CS1591
        [EnumMember(Value = "Friday")]
        #pragma warning disable CS1591
        Friday,
        #pragma warning restore CS1591
        [EnumMember(Value = "Saturday")]
        #pragma warning disable CS1591
        Saturday,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sunday")]
        #pragma warning disable CS1591
        Sunday,
        #pragma warning restore CS1591
    }
}
