// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the response message for the scheduled job.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChangeOwnerIsSuccessfullyScheduledMessage
    {
        [EnumMember(Value = "change owner is successfully scheduled")]
        #pragma warning disable CS1591
        ChangeOwnerIsSuccessfullyScheduled,
        #pragma warning restore CS1591
    }
}
