// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the error code for the territory validation failure. Possible values: INVALID_DATA - The territory ID is invalid. DUPLICATE_DATA - The territory is already associated with the user. PERMISSION_DENIED - The user lacks the required permission for the territory.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CommonErrorResponseTerritoriesItemCode
    {
        [EnumMember(Value = "INVALID_DATA")]
        #pragma warning disable CS1591
        InvalidData,
        #pragma warning restore CS1591
        [EnumMember(Value = "DUPLICATE_DATA")]
        #pragma warning disable CS1591
        DuplicateData,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERMISSION_DENIED")]
        #pragma warning disable CS1591
        PermissionDenied,
        #pragma warning restore CS1591
    }
}
