// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>HTTP method for the request</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CompositeRequestsComposite_composite_requests_method
    {
        [EnumMember(Value = "GET")]
        #pragma warning disable CS1591
        GET,
        #pragma warning restore CS1591
        [EnumMember(Value = "POST")]
        #pragma warning disable CS1591
        POST,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUT")]
        #pragma warning disable CS1591
        PUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETE")]
        #pragma warning disable CS1591
        DELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PATCH")]
        #pragma warning disable CS1591
        PATCH,
        #pragma warning restore CS1591
    }
}
