// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Number formatting style: Indian (1,00,000) vs International (100,000).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CurrenciesGetCurrencies200ResponseCurrenciesItemFormatNumeralSystem
    {
        [EnumMember(Value = "Indian")]
        #pragma warning disable CS1591
        Indian,
        #pragma warning restore CS1591
        [EnumMember(Value = "International")]
        #pragma warning disable CS1591
        International,
        #pragma warning restore CS1591
    }
}
