// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>A message describing the error.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DataSharingUpdateDataSharing400ResponseDataSharingItemMessage
    {
        [EnumMember(Value = "invalid data")]
        #pragma warning disable CS1591
        InvalidData,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cannot change the data sharing setting as module is made public in portals")]
        #pragma warning disable CS1591
        CannotChangeTheDataSharingSettingAsModuleIsMadePublicInPortals,
        #pragma warning restore CS1591
    }
}
