// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>is job sheet required for the service</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DataNestedBase_Job_Sheet_Required
    {
        [EnumMember(Value = "No")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
    }
}
