// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the trigger type for date or datetime-based rules, which fire relative to a date field value on the record.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DateOrDatetimeType
    {
        [EnumMember(Value = "date_or_datetime")]
        #pragma warning disable CS1591
        DateOrDatetime,
        #pragma warning restore CS1591
    }
}
