// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Error code identifying the issue</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Download_inline_images_getDownloadInlineImages_400_code
    {
        [EnumMember(Value = "INVALID_URL_PATTERN")]
        #pragma warning disable CS1591
        INVALID_URL_PATTERN,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_DATA")]
        #pragma warning disable CS1591
        INVALID_DATA,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_REQUEST_METHOD")]
        #pragma warning disable CS1591
        INVALID_REQUEST_METHOD,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_TOKEN")]
        #pragma warning disable CS1591
        INVALID_TOKEN,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_MODULE")]
        #pragma warning disable CS1591
        INVALID_MODULE,
        #pragma warning restore CS1591
    }
}
