// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the error message for the failure.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DurationValueShouldNotBeGreaterThan24HrsOrLessThan5MinsMessage
    {
        [EnumMember(Value = "Duration value should not be greater than 24hrs or less than 5mins")]
        #pragma warning disable CS1591
        DurationValueShouldNotBeGreaterThan24HrsOrLessThan5Mins,
        #pragma warning restore CS1591
    }
}
