// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Source of the schedule decision.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Email_drafts_getEmailDraft_200_email_drafts_schedule_details_source
    {
        [EnumMember(Value = "ecOneHourAhead")]
        #pragma warning disable CS1591
        EcOneHourAhead,
        #pragma warning restore CS1591
        [EnumMember(Value = "upTime")]
        #pragma warning disable CS1591
        UpTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "ecSchduleBestTime")]
        #pragma warning disable CS1591
        EcSchduleBestTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "ecUpComing")]
        #pragma warning disable CS1591
        EcUpComing,
        #pragma warning restore CS1591
        [EnumMember(Value = "ecSchduleTime")]
        #pragma warning disable CS1591
        EcSchduleTime,
        #pragma warning restore CS1591
    }
}
