// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Error message corresponding to the error code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmailsSharingDetailsGetEmailSharingDetail400_message
    {
        [EnumMember(Value = "The given data is invalid.")]
        #pragma warning disable CS1591
        TheGivenDataIsInvalid,
        #pragma warning restore CS1591
        [EnumMember(Value = "The module API name is invalid.")]
        #pragma warning disable CS1591
        TheModuleAPINameIsInvalid,
        #pragma warning restore CS1591
    }
}
