// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents the field update trigger details, including the criteria that define which field value change activates the rule.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecuteWhenT2FieldUpdateDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents the field value change criteria that activate the trigger. Defines which field is monitored and what change condition fires the rule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsCriteria? Criteria { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsCriteria Criteria { get; set; }
#endif
        /// <summary>Controls the logic applied across criteria groups.Possible values:true - All criteria groups must match (AND logic).false - Any one criteria group is sufficient (OR logic).</summary>
        public bool? MatchAll { get; set; }
        /// <summary>Indicates whether the rule fires every time the field update condition is met. When false, the rule fires only on the first occurrence.</summary>
        public bool? Repeat { get; set; }
        /// <summary>The module that actually triggers the rule. Defaults to the rule&apos;s top-level module if omitted. Must be explicitly set when the trigger targets a different module  - e.g., a rule on Leads triggered by &apos;note created&apos; requires trigger_module = {api_name: &apos;Notes&apos;, id: &apos;...&apos;}. Use `getModules` to discover module api_name and id values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsTriggerModule? TriggerModule { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsTriggerModule TriggerModule { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetails"/> and sets the default values.
        /// </summary>
        public ExecuteWhenT2FieldUpdateDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "criteria", n => { Criteria = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsCriteria>(global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsCriteria.CreateFromDiscriminatorValue); } },
                { "match_all", n => { MatchAll = n.GetBoolValue(); } },
                { "repeat", n => { Repeat = n.GetBoolValue(); } },
                { "trigger_module", n => { TriggerModule = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsTriggerModule>(global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsTriggerModule.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsCriteria>("criteria", Criteria);
            writer.WriteBoolValue("match_all", MatchAll);
            writer.WriteBoolValue("repeat", Repeat);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenT2FieldUpdateDetailsTriggerModule>("trigger_module", TriggerModule);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
