// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the trigger type for section update rules. Use getWorkflowConfigurations to verify the trigger is available for the target module.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExecuteWhenT3SectionUpdateType
    {
        [EnumMember(Value = "section_update")]
        #pragma warning disable CS1591
        SectionUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "incoming_call_section_update")]
        #pragma warning disable CS1591
        IncomingCallSectionUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "outgoing_call_section_update")]
        #pragma warning disable CS1591
        OutgoingCallSectionUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "scheduled_call_section_update")]
        #pragma warning disable CS1591
        ScheduledCallSectionUpdate,
        #pragma warning restore CS1591
    }
}
