// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>&quot;Field: type&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FieldMappings_type
    {
        [EnumMember(Value = "static")]
        #pragma warning disable CS1591
        Static,
        #pragma warning restore CS1591
        [EnumMember(Value = "merge_field")]
        #pragma warning disable CS1591
        Merge_field,
        #pragma warning restore CS1591
        [EnumMember(Value = "execution_time")]
        #pragma warning disable CS1591
        Execution_time,
        #pragma warning restore CS1591
    }
}
