// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents the active currency configuration for this field, specifying the decimal precision and rounding rule applied when storing and displaying monetary values.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FieldSchemaCurrencyOneOf1 : IParsable
    {
        /// <summary>Indicates the number of decimal places retained when storing and displaying currency values for this field, controlling the granularity of monetary amounts.</summary>
        public int? Precision { get; set; }
        /// <summary>Specifies the rounding rule applied to currency values when the raw amount exceeds the configured precision. Possible values: `round_up` — always rounds the value up. `round_down` — always rounds the value down. `round_off` — rounds to the nearest value. `normal` — no rounding applied.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.FieldSchemaCurrencyOneOf1RoundingOption? RoundingOption { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.FieldSchemaCurrencyOneOf1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.FieldSchemaCurrencyOneOf1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.FieldSchemaCurrencyOneOf1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "precision", n => { Precision = n.GetIntValue(); } },
                { "rounding_option", n => { RoundingOption = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.FieldSchemaCurrencyOneOf1RoundingOption>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("precision", Precision);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.FieldSchemaCurrencyOneOf1RoundingOption>("rounding_option", RoundingOption);
        }
    }
}
#pragma warning restore CS0618
