// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Specify the aggregation function.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FieldRequestBodySchemaFieldsItemRollupSummaryExpressionFunction
    {
        [EnumMember(Value = "SUM")]
        #pragma warning disable CS1591
        Sum,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNT")]
        #pragma warning disable CS1591
        Count,
        #pragma warning restore CS1591
        [EnumMember(Value = "AVG")]
        #pragma warning disable CS1591
        Avg,
        #pragma warning restore CS1591
        [EnumMember(Value = "MIN")]
        #pragma warning disable CS1591
        Min,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAX")]
        #pragma warning disable CS1591
        Max,
        #pragma warning restore CS1591
    }
}
