// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Zoho.OpenApiClient.Models.CustomFiscalYearPartialUpdate"/>, <see cref="global::Soenneker.Zoho.OpenApiClient.Models.DisplayBasedOnFiscalYearUpdate"/>, <see cref="global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate"/>, <see cref="global::Soenneker.Zoho.OpenApiClient.Models.SwitchToCustomFiscalYearUpdate"/>, <see cref="global::Soenneker.Zoho.OpenApiClient.Models.SwitchToStandardFiscalYearUpdate"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FiscalYearNested : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.CustomFiscalYearPartialUpdate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.CustomFiscalYearPartialUpdate? CustomFiscalYearPartialUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.CustomFiscalYearPartialUpdate CustomFiscalYearPartialUpdate { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.DisplayBasedOnFiscalYearUpdate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.DisplayBasedOnFiscalYearUpdate? DisplayBasedOnFiscalYearUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.DisplayBasedOnFiscalYearUpdate DisplayBasedOnFiscalYearUpdate { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate? StandardFiscalYearUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate StandardFiscalYearUpdate { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.SwitchToCustomFiscalYearUpdate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.SwitchToCustomFiscalYearUpdate? SwitchToCustomFiscalYearUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.SwitchToCustomFiscalYearUpdate SwitchToCustomFiscalYearUpdate { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.SwitchToStandardFiscalYearUpdate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.SwitchToStandardFiscalYearUpdate? SwitchToStandardFiscalYearUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.SwitchToStandardFiscalYearUpdate SwitchToStandardFiscalYearUpdate { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearNested"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearNested CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearNested();
            if("DisplayBasedOnFiscalYearUpdate".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DisplayBasedOnFiscalYearUpdate = new global::Soenneker.Zoho.OpenApiClient.Models.DisplayBasedOnFiscalYearUpdate();
            }
            else if("StandardFiscalYearUpdate".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.StandardFiscalYearUpdate = new global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate();
            }
            else if("SwitchToCustomFiscalYearUpdate".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SwitchToCustomFiscalYearUpdate = new global::Soenneker.Zoho.OpenApiClient.Models.SwitchToCustomFiscalYearUpdate();
            }
            else if("SwitchToStandardFiscalYearUpdate".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SwitchToStandardFiscalYearUpdate = new global::Soenneker.Zoho.OpenApiClient.Models.SwitchToStandardFiscalYearUpdate();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CustomFiscalYearPartialUpdate != null)
            {
                return CustomFiscalYearPartialUpdate.GetFieldDeserializers();
            }
            else if(DisplayBasedOnFiscalYearUpdate != null)
            {
                return DisplayBasedOnFiscalYearUpdate.GetFieldDeserializers();
            }
            else if(StandardFiscalYearUpdate != null)
            {
                return StandardFiscalYearUpdate.GetFieldDeserializers();
            }
            else if(SwitchToCustomFiscalYearUpdate != null)
            {
                return SwitchToCustomFiscalYearUpdate.GetFieldDeserializers();
            }
            else if(SwitchToStandardFiscalYearUpdate != null)
            {
                return SwitchToStandardFiscalYearUpdate.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CustomFiscalYearPartialUpdate != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.CustomFiscalYearPartialUpdate>(null, CustomFiscalYearPartialUpdate);
            }
            else if(DisplayBasedOnFiscalYearUpdate != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.DisplayBasedOnFiscalYearUpdate>(null, DisplayBasedOnFiscalYearUpdate);
            }
            else if(StandardFiscalYearUpdate != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate>(null, StandardFiscalYearUpdate);
            }
            else if(SwitchToCustomFiscalYearUpdate != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.SwitchToCustomFiscalYearUpdate>(null, SwitchToCustomFiscalYearUpdate);
            }
            else if(SwitchToStandardFiscalYearUpdate != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.SwitchToStandardFiscalYearUpdate>(null, SwitchToStandardFiscalYearUpdate);
            }
        }
    }
}
#pragma warning restore CS0618
