// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Type of the action (Required)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FollowupActionsResponseObject_type
    {
        [EnumMember(Value = "tasks")]
        #pragma warning disable CS1591
        Tasks,
        #pragma warning restore CS1591
    }
}
