// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Nested schema for Blueprint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GETBlueprintNested : IParsable
    {
        /// <summary>Nested schema for 3060320000000666022</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.GET3060320000000666022Nested1? ThreeZeroSixZeroThreeTwoZeroZeroZeroZeroZeroZeroZeroSixSixSixZeroTwoTwo { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.GET3060320000000666022Nested1 ThreeZeroSixZeroThreeTwoZeroZeroZeroZeroZeroZeroZeroSixSixSixZeroTwoTwo { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.GETBlueprintNested"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.GETBlueprintNested CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.GETBlueprintNested();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "3060320000000666022", n => { ThreeZeroSixZeroThreeTwoZeroZeroZeroZeroZeroZeroZeroSixSixSixZeroTwoTwo = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.GET3060320000000666022Nested1>(global::Soenneker.Zoho.OpenApiClient.Models.GET3060320000000666022Nested1.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.GET3060320000000666022Nested1>("3060320000000666022", ThreeZeroSixZeroThreeTwoZeroZeroZeroZeroZeroZeroZeroSixSixSixZeroTwoTwo);
        }
    }
}
#pragma warning restore CS0618
