// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents the execution frequency and unenrollment configuration for the Cadence.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetByIdCadenceSuccessRespCadencesItemExecutionDetails : IParsable
    {
        /// <summary>Represents the recurring execution interval for a Cadence, specifying the frequency period and numeric value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.ExecuteEvery? ExecuteEvery { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.ExecuteEvery ExecuteEvery { get; set; }
#endif
        /// <summary>Represents the list of conditions under which records are automatically unenrolled from the Cadence.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.GetByIdCadenceSuccessRespCadencesItemExecutionDetailsUnenrollPropertiesItem>? UnenrollProperties { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.GetByIdCadenceSuccessRespCadencesItemExecutionDetailsUnenrollPropertiesItem> UnenrollProperties { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.GetByIdCadenceSuccessRespCadencesItemExecutionDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.GetByIdCadenceSuccessRespCadencesItemExecutionDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.GetByIdCadenceSuccessRespCadencesItemExecutionDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "execute_every", n => { ExecuteEvery = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ExecuteEvery>(global::Soenneker.Zoho.OpenApiClient.Models.ExecuteEvery.CreateFromDiscriminatorValue); } },
                { "unenroll_properties", n => { UnenrollProperties = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.GetByIdCadenceSuccessRespCadencesItemExecutionDetailsUnenrollPropertiesItem>(global::Soenneker.Zoho.OpenApiClient.Models.GetByIdCadenceSuccessRespCadencesItemExecutionDetailsUnenrollPropertiesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ExecuteEvery>("execute_every", ExecuteEvery);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.GetByIdCadenceSuccessRespCadencesItemExecutionDetailsUnenrollPropertiesItem>("unenroll_properties", UnenrollProperties);
        }
    }
}
#pragma warning restore CS0618
