// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>The error code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetRelatedRecordsCountErrorResponse_code
    {
        [EnumMember(Value = "INVALID_DATA")]
        #pragma warning disable CS1591
        INVALID_DATA,
        #pragma warning restore CS1591
        [EnumMember(Value = "PATTERN_NOT_MATCHED")]
        #pragma warning disable CS1591
        PATTERN_NOT_MATCHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANDATORY_NOT_FOUND")]
        #pragma warning disable CS1591
        MANDATORY_NOT_FOUND,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPECTED_FIELD_MISSING")]
        #pragma warning disable CS1591
        EXPECTED_FIELD_MISSING,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_SUPPORTED")]
        #pragma warning disable CS1591
        NOT_SUPPORTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPENDENT_FIELD_MISMATCH")]
        #pragma warning disable CS1591
        DEPENDENT_FIELD_MISMATCH,
        #pragma warning restore CS1591
    }
}
