// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the user&apos;s preferred unit of measurement for displaying distance values.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetUserDetailsDistancePreferenceS
    {
        [EnumMember(Value = "Kilometers")]
        #pragma warning disable CS1591
        Kilometers,
        #pragma warning restore CS1591
        [EnumMember(Value = "Miles")]
        #pragma warning disable CS1591
        Miles,
        #pragma warning restore CS1591
    }
}
