// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Picklist value object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GlobalPicklistsGetSingleGlobalPicklists200_global_picklists_pick_list_values : IParsable
    {
        /// <summary>Actual value of the picklist field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActualValue { get; set; }
#nullable restore
#else
        public string ActualValue { get; set; }
#endif
        /// <summary>The picklist display value(translated value if translation enabled).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayValue { get; set; }
#nullable restore
#else
        public string DisplayValue { get; set; }
#endif
        /// <summary>Id of the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Reference value of the picklist field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReferenceValue { get; set; }
#nullable restore
#else
        public string ReferenceValue { get; set; }
#endif
        /// <summary>Sequence number of the picklist value.</summary>
        public int? SequenceNumber { get; set; }
        /// <summary>Type of the picklist value (used or unused).</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.GlobalPicklistsGetSingleGlobalPicklists200_global_picklists_pick_list_values_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.GlobalPicklistsGetSingleGlobalPicklists200_global_picklists_pick_list_values"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.GlobalPicklistsGetSingleGlobalPicklists200_global_picklists_pick_list_values CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.GlobalPicklistsGetSingleGlobalPicklists200_global_picklists_pick_list_values();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actual_value", n => { ActualValue = n.GetStringValue(); } },
                { "display_value", n => { DisplayValue = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "reference_value", n => { ReferenceValue = n.GetStringValue(); } },
                { "sequence_number", n => { SequenceNumber = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.GlobalPicklistsGetSingleGlobalPicklists200_global_picklists_pick_list_values_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("actual_value", ActualValue);
            writer.WriteStringValue("display_value", DisplayValue);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("reference_value", ReferenceValue);
            writer.WriteIntValue("sequence_number", SequenceNumber);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.GlobalPicklistsGetSingleGlobalPicklists200_global_picklists_pick_list_values_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
