// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Specify the details for a single holiday to create.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HolidaysCreateHolidaysRequestHolidaysItem : IParsable
    {
        /// <summary>Specify the date of the holiday in **YYYY-MM-DD** format.</summary>
        public Date? Date { get; set; }
        /// <summary>Specify the name of the holiday.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Specify the shift hour associated with this holiday. Required when the type field is set to **shift_holiday**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItemShiftHour? ShiftHour { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItemShiftHour ShiftHour { get; set; }
#endif
        /// <summary>Specify the type of holiday. Possible values: **business_holiday**, **shift_holiday**.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItemType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date", n => { Date = n.GetDateValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "shift_hour", n => { ShiftHour = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItemShiftHour>(global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItemShiftHour.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItemType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("date", Date);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItemShiftHour>("shift_hour", ShiftHour);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.HolidaysCreateHolidaysRequestHolidaysItemType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
