// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LayoutResponseSchema_layouts_sections_properties : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bulk_addition property</summary>
        public bool? BulkAddition { get; set; }
        /// <summary>Maximum number of rows allowed in the subform</summary>
        public int? MaximumRows { get; set; }
        /// <summary>Filter preference criteria for the section. Defines conditions that must be met for the section to be displayed or for certain behaviors to apply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_preference>? Preference { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_preference> Preference { get; set; }
#endif
        /// <summary>Allows reordering of subform rows</summary>
        public bool? ReorderRows { get; set; }
        /// <summary>The tooltip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_tooltip? Tooltip { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_tooltip Tooltip { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties"/> and sets the default values.
        /// </summary>
        public LayoutResponseSchema_layouts_sections_properties()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bulk_addition", n => { BulkAddition = n.GetBoolValue(); } },
                { "maximum_rows", n => { MaximumRows = n.GetIntValue(); } },
                { "preference", n => { Preference = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_preference>(global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_preference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reorder_rows", n => { ReorderRows = n.GetBoolValue(); } },
                { "tooltip", n => { Tooltip = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_tooltip>(global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_tooltip.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("bulk_addition", BulkAddition);
            writer.WriteIntValue("maximum_rows", MaximumRows);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_preference>("preference", Preference);
            writer.WriteBoolValue("reorder_rows", ReorderRows);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.LayoutResponseSchema_layouts_sections_properties_tooltip>("tooltip", Tooltip);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
