// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember1"/>, <see cref="global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LayoutsFieldSchemaMaskDetails : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember1? LayoutsFieldSchemaMaskDetailsMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember1 LayoutsFieldSchemaMaskDetailsMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember2? LayoutsFieldSchemaMaskDetailsMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember2 LayoutsFieldSchemaMaskDetailsMember2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetails();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LayoutsFieldSchemaMaskDetailsMember1 = new global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LayoutsFieldSchemaMaskDetailsMember2 = new global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(LayoutsFieldSchemaMaskDetailsMember1 != null)
            {
                return LayoutsFieldSchemaMaskDetailsMember1.GetFieldDeserializers();
            }
            else if(LayoutsFieldSchemaMaskDetailsMember2 != null)
            {
                return LayoutsFieldSchemaMaskDetailsMember2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(LayoutsFieldSchemaMaskDetailsMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember1>(null, LayoutsFieldSchemaMaskDetailsMember1);
            }
            else if(LayoutsFieldSchemaMaskDetailsMember2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaMaskDetailsMember2>(null, LayoutsFieldSchemaMaskDetailsMember2);
            }
        }
    }
}
#pragma warning restore CS0618
