// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Query configuration with filter criteria for filtering lookup options.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LayoutsFieldSchemaLookup_query_detailsMember1 : IParsable
    {
        /// <summary>Filter criteria configuration for the lookup query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaLookup_query_detailsMember1_criteria? Criteria { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaLookup_query_detailsMember1_criteria Criteria { get; set; }
#endif
        /// <summary>Unique identifier of the query used to filter lookup options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch? QueryId { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch QueryId { get; set; }
#endif
        /// <summary>System-generated query ID for filtering lookup options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch? SystemQueryId { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch SystemQueryId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaLookup_query_detailsMember1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaLookup_query_detailsMember1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaLookup_query_detailsMember1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "criteria", n => { Criteria = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaLookup_query_detailsMember1_criteria>(global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaLookup_query_detailsMember1_criteria.CreateFromDiscriminatorValue); } },
                { "query_id", n => { QueryId = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch>(global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch.CreateFromDiscriminatorValue); } },
                { "system_query_id", n => { SystemQueryId = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch>(global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.LayoutsFieldSchemaLookup_query_detailsMember1_criteria>("criteria", Criteria);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch>("query_id", QueryId);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.UnionBranch>("system_query_id", SystemQueryId);
        }
    }
}
#pragma warning restore CS0618
