// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Status category.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Mass_convert_getJobStatus_403_status
    {
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
