// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Required permission identifier</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModulesCreateModules403_details_permissions
    {
        [EnumMember(Value = "Crm_Implied_Customize_Zoho_CRM")]
        #pragma warning disable CS1591
        Crm_Implied_Customize_Zoho_CRM,
        #pragma warning restore CS1591
    }
}
