// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Type of the name field. &apos;autonumber&apos; for auto-generated sequential IDs (requires auto_number configuration), &apos;text&apos; for user-entered text. Mandatory if display_field is provided and field_label is not specified.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModulesCreateModules_modules_display_field_data_type
    {
        [EnumMember(Value = "autonumber")]
        #pragma warning disable CS1591
        Autonumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
    }
}
