// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Access control scope for the module. Possible values: org_based - organization-wide access; team_based - team-specific access. Immutable after module creation; cannot be changed via PUT.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModulesGetModuleByApiName200ResponseModulesItemAccessType
    {
        [EnumMember(Value = "org_based")]
        #pragma warning disable CS1591
        OrgBased,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_based")]
        #pragma warning disable CS1591
        TeamBased,
        #pragma warning restore CS1591
    }
}
