// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Access control type for the module; `org_based` grants organization-wide access and `team_based` grants team-specific access. This value is immutable after module creation and cannot be updated via PUT operations.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModulesGetModules200ResponseModulesItemAccessType
    {
        [EnumMember(Value = "org_based")]
        #pragma warning disable CS1591
        OrgBased,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_based")]
        #pragma warning disable CS1591
        TeamBased,
        #pragma warning restore CS1591
    }
}
