// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Set of allowed record-level operations within this related list, such as create, edit, and assign.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModulesGetModuleByApiName200ResponseModulesItemRelatedListsItemRecordOperations : IParsable
    {
        /// <summary>True when the assign operation is permitted for records in this related list.</summary>
        public bool? Assign { get; set; }
        /// <summary>True when bulk edit of records in this related list is permitted for the current user.</summary>
        public bool? BulkEdit { get; set; }
        /// <summary>True when creation of records within this related list is permitted for the current user.</summary>
        public bool? Create { get; set; }
        /// <summary>True when deletion of associated records from this related list is permitted for the current user.</summary>
        public bool? Delete { get; set; }
        /// <summary>True when disassociation of records from this related list is permitted for the current user.</summary>
        public bool? Disassociate { get; set; }
        /// <summary>True when editing of records within this related list is permitted for the current user.</summary>
        public bool? Edit { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.ModulesGetModuleByApiName200ResponseModulesItemRelatedListsItemRecordOperations"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.ModulesGetModuleByApiName200ResponseModulesItemRelatedListsItemRecordOperations CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.ModulesGetModuleByApiName200ResponseModulesItemRelatedListsItemRecordOperations();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assign", n => { Assign = n.GetBoolValue(); } },
                { "bulk_edit", n => { BulkEdit = n.GetBoolValue(); } },
                { "create", n => { Create = n.GetBoolValue(); } },
                { "delete", n => { Delete = n.GetBoolValue(); } },
                { "disassociate", n => { Disassociate = n.GetBoolValue(); } },
                { "edit", n => { Edit = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("assign", Assign);
            writer.WriteBoolValue("bulk_edit", BulkEdit);
            writer.WriteBoolValue("create", Create);
            writer.WriteBoolValue("delete", Delete);
            writer.WriteBoolValue("disassociate", Disassociate);
            writer.WriteBoolValue("edit", Edit);
        }
    }
}
#pragma warning restore CS0618
