// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents a CRM module with its identity and display labels, including its API name, singular and plural display labels, unique ID, and internal name.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModuleReference : IParsable
    {
        /// <summary>Represents the API name of the CRM module used in API requests (for example, Leads, Contacts, Deals, Accounts, Tasks, Cases, Products, Quotes, Sales_Orders, Invoices, Campaigns, Vendors).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiName { get; set; }
#nullable restore
#else
        public string ApiName { get; set; }
#endif
        /// <summary>Represents the unique identifier of the CRM module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Represents the internal name of the CRM module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Represents the plural display name of the module as shown in the CRM UI (for example, Leads, Contacts, Deals).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PluralLabel { get; set; }
#nullable restore
#else
        public string PluralLabel { get; set; }
#endif
        /// <summary>Represents the singular display name of the module as shown in the CRM UI (for example, Lead, Contact, Deal).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SingularLabel { get; set; }
#nullable restore
#else
        public string SingularLabel { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.ModuleReference"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.ModuleReference CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.ModuleReference();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_name", n => { ApiName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "plural_label", n => { PluralLabel = n.GetStringValue(); } },
                { "singular_label", n => { SingularLabel = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_name", ApiName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("plural_label", PluralLabel);
            writer.WriteStringValue("singular_label", SingularLabel);
        }
    }
}
#pragma warning restore CS0618
