// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Classification of this related list. Possible values: default - standard related list; multiselectlookup - multi-select lookup; combined_view - combined view; custom_lookup - custom lookup; custom_related_list - custom related list; slyteui - Slyte UI; queries - query-based; custom_function - function-based; grouped - grouped list.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModulesGetModuleByApiName200ResponseModulesItemRelatedListsItemType
    {
        [EnumMember(Value = "multiselectlookup")]
        #pragma warning disable CS1591
        Multiselectlookup,
        #pragma warning restore CS1591
        [EnumMember(Value = "combined_view")]
        #pragma warning disable CS1591
        CombinedView,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_lookup")]
        #pragma warning disable CS1591
        CustomLookup,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_related_list")]
        #pragma warning disable CS1591
        CustomRelatedList,
        #pragma warning restore CS1591
        [EnumMember(Value = "slyteui")]
        #pragma warning disable CS1591
        Slyteui,
        #pragma warning restore CS1591
        [EnumMember(Value = "queries")]
        #pragma warning disable CS1591
        Queries,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_function")]
        #pragma warning disable CS1591
        CustomFunction,
        #pragma warning restore CS1591
        [EnumMember(Value = "grouped")]
        #pragma warning disable CS1591
        Grouped,
        #pragma warning restore CS1591
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        DefaultValue,
        #pragma warning restore CS1591
    }
}
