// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// An array of action objects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NonAssociateActionsNestedSchema : IParsable
    {
        /// <summary>Specify the details of the action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchemaDetails? Details { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchemaDetails Details { get; set; }
#endif
        /// <summary>Unique identifier for the non-associate action.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Specify the action name (Required)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The related_details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedDetailsNestedSchema? RelatedDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedDetailsNestedSchema RelatedDetails { get; set; }
#endif
        /// <summary>Specify the type of action (Required)</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchema_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "details", n => { Details = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchemaDetails>(global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchemaDetails.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "related_details", n => { RelatedDetails = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedDetailsNestedSchema>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedDetailsNestedSchema.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchema_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchemaDetails>("details", Details);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedDetailsNestedSchema>("related_details", RelatedDetails);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.NonAssociateActionsNestedSchema_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
