// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Machine-readable error code indicating the type of error (e.g., &apos;NO_PERMISSION&apos;).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NoPermissionErrorResponse_code
    {
        [EnumMember(Value = "NO_PERMISSION")]
        #pragma warning disable CS1591
        NO_PERMISSION,
        #pragma warning restore CS1591
    }
}
