// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the error code that identifies the specific error condition.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NoPermissionSchemaCode
    {
        [EnumMember(Value = "NO_PERMISSION")]
        #pragma warning disable CS1591
        NoPermission,
        #pragma warning restore CS1591
        [EnumMember(Value = "FEATURE_NOT_SUPPORTED")]
        #pragma warning disable CS1591
        FeatureNotSupported,
        #pragma warning restore CS1591
    }
}
