// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Update specific notification info request wrapper.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotificationsUpdateNotificationInfo : IParsable
    {
        /// <summary>New expiry timestamp (&lt;= 1 week).</summary>
        public DateTimeOffset? ChannelExpiry { get; set; }
        /// <summary>Channel identifier to update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelId { get; set; }
#nullable restore
#else
        public string ChannelId { get; set; }
#endif
        /// <summary>Updated event subscriptions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Events { get; set; }
#nullable restore
#else
        public List<string> Events { get; set; }
#endif
        /// <summary>Conditional field selection groups (max 2 objects).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.NotificationsUpdateNotificationInfo_notification_condition>? NotificationCondition { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.NotificationsUpdateNotificationInfo_notification_condition> NotificationCondition { get; set; }
#endif
        /// <summary>Notify on related action flag.</summary>
        public bool? NotifyOnRelatedAction { get; set; }
        /// <summary>Destination callback URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotifyUrl { get; set; }
#nullable restore
#else
        public string NotifyUrl { get; set; }
#endif
        /// <summary>Return affected field values in notification payloads.</summary>
        public bool? ReturnAffectedFieldValues { get; set; }
        /// <summary>Verification token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.NotificationsUpdateNotificationInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.NotificationsUpdateNotificationInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.NotificationsUpdateNotificationInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channel_expiry", n => { ChannelExpiry = n.GetDateTimeOffsetValue(); } },
                { "channel_id", n => { ChannelId = n.GetStringValue(); } },
                { "events", n => { Events = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "notification_condition", n => { NotificationCondition = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.NotificationsUpdateNotificationInfo_notification_condition>(global::Soenneker.Zoho.OpenApiClient.Models.NotificationsUpdateNotificationInfo_notification_condition.CreateFromDiscriminatorValue)?.AsList(); } },
                { "notify_on_related_action", n => { NotifyOnRelatedAction = n.GetBoolValue(); } },
                { "notify_url", n => { NotifyUrl = n.GetStringValue(); } },
                { "return_affected_field_values", n => { ReturnAffectedFieldValues = n.GetBoolValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("channel_expiry", ChannelExpiry);
            writer.WriteStringValue("channel_id", ChannelId);
            writer.WriteCollectionOfPrimitiveValues<string>("events", Events);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.NotificationsUpdateNotificationInfo_notification_condition>("notification_condition", NotificationCondition);
            writer.WriteBoolValue("notify_on_related_action", NotifyOnRelatedAction);
            writer.WriteStringValue("notify_url", NotifyUrl);
            writer.WriteBoolValue("return_affected_field_values", ReturnAffectedFieldValues);
            writer.WriteStringValue("token", Token);
        }
    }
}
#pragma warning restore CS0618
