// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// User invitation details
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PortalUsersInviteUsers_portal_invite_data : IParsable
    {
        /// <summary>User record ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Preferred language for the invitation</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data_language? Language { get; set; }
        /// <summary>Invitation type</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data_type? Type { get; set; }
        /// <summary>User type identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserTypeId { get; set; }
#nullable restore
#else
        public string UserTypeId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "language", n => { Language = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data_language>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data_type>(); } },
                { "user_type_id", n => { UserTypeId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data_language>("language", Language);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersInviteUsers_portal_invite_data_type>("type", Type);
            writer.WriteStringValue("user_type_id", UserTypeId);
        }
    }
}
#pragma warning restore CS0618
