// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Module object for assignment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PortalUserTypeCreatePortalUserType_user_type_modules : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>API name of the module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiName { get; set; }
#nullable restore
#else
        public string ApiName { get; set; }
#endif
        /// <summary>Custom views for the module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_custom_views>? CustomViews { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_custom_views> CustomViews { get; set; }
#endif
        /// <summary>Fields accessible in the module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_fields>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_fields> Fields { get; set; }
#endif
        /// <summary>Filters available for the module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_filters>? Filters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_filters> Filters { get; set; }
#endif
        /// <summary>Module id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Layouts available for the module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_layouts>? Layouts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_layouts> Layouts { get; set; }
#endif
        /// <summary>Permissions for the module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_permissions? Permissions { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_permissions Permissions { get; set; }
#endif
        /// <summary>Plural label for the module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PluralLabel { get; set; }
#nullable restore
#else
        public string PluralLabel { get; set; }
#endif
        /// <summary>Shared type of the module.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_shared_type? SharedType { get; set; }
        /// <summary>View object for the module.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_views? Views { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_views Views { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules"/> and sets the default values.
        /// </summary>
        public PortalUserTypeCreatePortalUserType_user_type_modules()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_name", n => { ApiName = n.GetStringValue(); } },
                { "custom_views", n => { CustomViews = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_custom_views>(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_custom_views.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_fields>(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_fields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_filters>(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_filters.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "layouts", n => { Layouts = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_layouts>(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_layouts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "permissions", n => { Permissions = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_permissions>(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_permissions.CreateFromDiscriminatorValue); } },
                { "plural_label", n => { PluralLabel = n.GetStringValue(); } },
                { "shared_type", n => { SharedType = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_shared_type>(); } },
                { "views", n => { Views = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_views>(global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_views.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_name", ApiName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_custom_views>("custom_views", CustomViews);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_fields>("fields", Fields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_filters>("filters", Filters);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_layouts>("layouts", Layouts);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_permissions>("permissions", Permissions);
            writer.WriteStringValue("plural_label", PluralLabel);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_shared_type>("shared_type", SharedType);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUserTypeCreatePortalUserType_user_type_modules_views>("views", Views);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
