// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Portal change status response object
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PortalUsersChangePortalUsersStatus200_change_status : IParsable
    {
        /// <summary>Status code indicating portal user status was changed</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_code? Code { get; set; }
        /// <summary>Additional details about the portal user status was changed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_details? Details { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_details Details { get; set; }
#endif
        /// <summary>Success message</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Status of the response</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_status? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_code>(); } },
                { "details", n => { Details = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_details>(global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_details.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_code>("code", Code);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_details>("details", Details);
            writer.WriteStringValue("message", Message);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.PortalUsersChangePortalUsersStatus200_change_status_status>("status", Status);
        }
    }
}
#pragma warning restore CS0618
