// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>A message indicating the result.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Record_share_email_unshareEmails_200_data_message
    {
        [EnumMember(Value = "Sharing revoked successfully")]
        #pragma warning disable CS1591
        SharingRevokedSuccessfully,
        #pragma warning restore CS1591
    }
}
