// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the error code returned for the record-locked failure.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RecordLockedCode
    {
        [EnumMember(Value = "RECORD_LOCKED")]
        #pragma warning disable CS1591
        RecordLocked,
        #pragma warning restore CS1591
    }
}
