// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RecordSortBy
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "Created_Time")]
        #pragma warning disable CS1591
        CreatedTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "Modified_Time")]
        #pragma warning disable CS1591
        ModifiedTime,
        #pragma warning restore CS1591
    }
}
