// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>The type of feature for which the record locking configuration is applied.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Record_locking_configurations_getRecordLockingConfiguration_200_record_locking_configurations_feature_type
    {
        [EnumMember(Value = "record_locking")]
        #pragma warning disable CS1591
        Record_locking,
        #pragma warning restore CS1591
    }
}
