// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Human-readable error message</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RecordCountGetRecordCount400ResponseMessage
    {
        [EnumMember(Value = "unable to process your request. please verify whether you have entered proper method name, parameter and parameter values.")]
        #pragma warning disable CS1591
        UnableToProcessYourRequestPleaseVerifyWhetherYouHaveEnteredProperMethodNameCommaParameterAndParameterValuesDot,
        #pragma warning restore CS1591
        [EnumMember(Value = "this data type is not found in this module")]
        #pragma warning disable CS1591
        ThisDataTypeIsNotFoundInThisModule,
        #pragma warning restore CS1591
        [EnumMember(Value = "The module does not support this operation")]
        #pragma warning disable CS1591
        TheModuleDoesNotSupportThisOperation,
        #pragma warning restore CS1591
        [EnumMember(Value = "module not suppoted for search")]
        #pragma warning disable CS1591
        ModuleNotSuppotedForSearch,
        #pragma warning restore CS1591
        [EnumMember(Value = "the given module is not supported for count")]
        #pragma warning disable CS1591
        TheGivenModuleIsNotSupportedForCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cannot use the restricted field.")]
        #pragma warning disable CS1591
        CannotUseTheRestrictedField,
        #pragma warning restore CS1591
        [EnumMember(Value = "Invalid query formed")]
        #pragma warning disable CS1591
        InvalidQueryFormed,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid value for search")]
        #pragma warning disable CS1591
        InvalidValueForSearch,
        #pragma warning restore CS1591
        [EnumMember(Value = "the field is not available for search")]
        #pragma warning disable CS1591
        TheFieldIsNotAvailableForSearch,
        #pragma warning restore CS1591
        [EnumMember(Value = "Please check the value of the field")]
        #pragma warning disable CS1591
        PleaseCheckTheValueOfTheField,
        #pragma warning restore CS1591
        [EnumMember(Value = "special characters are not allowed")]
        #pragma warning disable CS1591
        SpecialCharactersAreNotAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid operator found")]
        #pragma warning disable CS1591
        InvalidOperatorFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_masking_permission")]
        #pragma warning disable CS1591
        NoMaskingPermission,
        #pragma warning restore CS1591
        [EnumMember(Value = "More than one wildcard(*) not allowed in a searchword")]
        #pragma warning disable CS1591
        MoreThanOneWildcardLeftParenthesisAsteriskRightParenthesisNotAllowedInASearchword,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid data")]
        #pragma warning disable CS1591
        InvalidData,
        #pragma warning restore CS1591
        [EnumMember(Value = "provide atleast 2 letters for search")]
        #pragma warning disable CS1591
        ProvideAtleast2LettersForSearch,
        #pragma warning restore CS1591
        [EnumMember(Value = "Only 100 values are allowed in \"IN\" criteria")]
        #pragma warning disable CS1591
        Only100ValuesAreAllowedInQuoteINQuoteCriteria,
        #pragma warning restore CS1591
        [EnumMember(Value = "maximum response iteration limit reached")]
        #pragma warning disable CS1591
        MaximumResponseIterationLimitReached,
        #pragma warning restore CS1591
        [EnumMember(Value = "no of criterium that can be given exceed the limit 15")]
        #pragma warning disable CS1591
        NoOfCriteriumThatCanBeGivenExceedTheLimit15,
        #pragma warning restore CS1591
        [EnumMember(Value = "Please use either Cvid or Search Params. Combination of both the params is not allowed")]
        #pragma warning disable CS1591
        PleaseUseEitherCvidOrSearchParamsCombinationOfBothTheParamsIsNotAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "api not supported in this version")]
        #pragma warning disable CS1591
        ApiNotSupportedInThisVersion,
        #pragma warning restore CS1591
    }
}
