// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Configuration metadata for a related list of type multiselectlookup.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RelatedListMultiselectLookup : IParsable
    {
        /// <summary>Action type supported for adding records to the related list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>API name identifier for the related list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiName { get; set; }
#nullable restore
#else
        public string ApiName { get; set; }
#endif
        /// <summary>API name of the connected lookup field for this multiselectlookup related list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectedlookupApiName { get; set; }
#nullable restore
#else
        public string ConnectedlookupApiName { get; set; }
#endif
        /// <summary>API name of the connected module for this multiselectlookup relationship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Connectedmodule { get; set; }
#nullable restore
#else
        public string Connectedmodule { get; set; }
#endif
        /// <summary>Indicates whether the display label of this related list can be customized. Possible values: **true**, **false**. </summary>
        public bool? CustomizeDisplayLabel { get; set; }
        /// <summary>Indicates whether the field selection for this related list can be customized. Possible values: **true**, **false**. </summary>
        public bool? CustomizeFields { get; set; }
        /// <summary>Indicates whether the sort configuration for this related list can be customized. Possible values: **true**, **false**. </summary>
        public bool? CustomizeSort { get; set; }
        /// <summary>User-visible label displayed for the related list panel.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayLabel { get; set; }
#nullable restore
#else
        public string DisplayLabel { get; set; }
#endif
        /// <summary>Indicates whether the multiselectlookup field is enabled. Possible values: **true**, **false**.</summary>
        public bool? FieldEnabled { get; set; }
        /// <summary>List of fields configured as columns in the related list view.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListField>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListField> Fields { get; set; }
#endif
        /// <summary>Relative URL template for navigating to the related list records.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Href { get; set; }
#nullable restore
#else
        public string Href { get; set; }
#endif
        /// <summary>Specifies the unique identifier of the related list configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Layout-specific configuration overrides for this related list, such as per-layout sequence and visibility.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListLayoutSpecificProperty>? LayoutSpecificProperties { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListLayoutSpecificProperty> LayoutSpecificProperties { get; set; }
#endif
        /// <summary>API name of the linking module that connects the two entities in the multiselectlookup relationship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Linkingmodule { get; set; }
#nullable restore
#else
        public string Linkingmodule { get; set; }
#endif
        /// <summary>Module information for the related list. Refer to the [Get Modules](https://www.zoho.com/crm/developer/docs/api/v8/modules-api.html) resource for details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListModule? Module { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListModule Module { get; set; }
#endif
        /// <summary>Represents the multiselectlookup configuration for a related list, including the lookup field, linking module, and connected module details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.MultiselectLookupConfig? Multiselectlookup { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.MultiselectLookupConfig Multiselectlookup { get; set; }
#endif
        /// <summary>Internal name of the related list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>List of parent related list references that this related list depends on for contextual display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListParentReference>? ParentRelatedLists { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListParentReference> ParentRelatedLists { get; set; }
#endif
        /// <summary>Internal personality identifier associated with this related list configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonalityName { get; set; }
#nullable restore
#else
        public string PersonalityName { get; set; }
#endif
        /// <summary>Represents the set of record operations permitted for a related list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListRecordOperations? RecordOperations { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListRecordOperations RecordOperations { get; set; }
#endif
        /// <summary>Specifies the display sequence position of the related list in the layout.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceNumber { get; set; }
#nullable restore
#else
        public string SequenceNumber { get; set; }
#endif
        /// <summary>Field by which records in this related list are sorted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectSortField? SortBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectSortField SortBy { get; set; }
#endif
        /// <summary>Sort direction for records in this related list. Possible values: **asc**, **desc**.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookupSortOrder? SortOrder { get; set; }
        /// <summary>Visibility status of the related list. Possible values: **visible**, **user_hidden**, **scheduled_for_deletion**. </summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookupStatus? Status { get; set; }
        /// <summary>Relationship type of the related list.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.MultiselectlookupType? Type { get; set; }
        /// <summary>Numeric visibility flag for the related list.</summary>
        public int? Visibility { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "api_name", n => { ApiName = n.GetStringValue(); } },
                { "connectedlookupApiName", n => { ConnectedlookupApiName = n.GetStringValue(); } },
                { "connectedmodule", n => { Connectedmodule = n.GetStringValue(); } },
                { "customize_display_label", n => { CustomizeDisplayLabel = n.GetBoolValue(); } },
                { "customize_fields", n => { CustomizeFields = n.GetBoolValue(); } },
                { "customize_sort", n => { CustomizeSort = n.GetBoolValue(); } },
                { "display_label", n => { DisplayLabel = n.GetStringValue(); } },
                { "field_enabled", n => { FieldEnabled = n.GetBoolValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListField>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "href", n => { Href = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "_layout_specific_properties", n => { LayoutSpecificProperties = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListLayoutSpecificProperty>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListLayoutSpecificProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "linkingmodule", n => { Linkingmodule = n.GetStringValue(); } },
                { "module", n => { Module = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListModule>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListModule.CreateFromDiscriminatorValue); } },
                { "multiselectlookup", n => { Multiselectlookup = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.MultiselectLookupConfig>(global::Soenneker.Zoho.OpenApiClient.Models.MultiselectLookupConfig.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent_related_lists", n => { ParentRelatedLists = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListParentReference>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListParentReference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "personality_name", n => { PersonalityName = n.GetStringValue(); } },
                { "record_operations", n => { RecordOperations = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListRecordOperations>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListRecordOperations.CreateFromDiscriminatorValue); } },
                { "sequence_number", n => { SequenceNumber = n.GetStringValue(); } },
                { "sort_by", n => { SortBy = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectSortField>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectSortField.CreateFromDiscriminatorValue); } },
                { "sort_order", n => { SortOrder = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookupSortOrder>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookupStatus>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.MultiselectlookupType>(); } },
                { "visibility", n => { Visibility = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteStringValue("api_name", ApiName);
            writer.WriteStringValue("connectedlookupApiName", ConnectedlookupApiName);
            writer.WriteStringValue("connectedmodule", Connectedmodule);
            writer.WriteBoolValue("customize_display_label", CustomizeDisplayLabel);
            writer.WriteBoolValue("customize_fields", CustomizeFields);
            writer.WriteBoolValue("customize_sort", CustomizeSort);
            writer.WriteStringValue("display_label", DisplayLabel);
            writer.WriteBoolValue("field_enabled", FieldEnabled);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListField>("fields", Fields);
            writer.WriteStringValue("href", Href);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListLayoutSpecificProperty>("_layout_specific_properties", LayoutSpecificProperties);
            writer.WriteStringValue("linkingmodule", Linkingmodule);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListModule>("module", Module);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.MultiselectLookupConfig>("multiselectlookup", Multiselectlookup);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListParentReference>("parent_related_lists", ParentRelatedLists);
            writer.WriteStringValue("personality_name", PersonalityName);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListRecordOperations>("record_operations", RecordOperations);
            writer.WriteStringValue("sequence_number", SequenceNumber);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectSortField>("sort_by", SortBy);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookupSortOrder>("sort_order", SortOrder);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListMultiselectLookupStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.MultiselectlookupType>("type", Type);
            writer.WriteIntValue("visibility", Visibility);
        }
    }
}
#pragma warning restore CS0618
