// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents a field configured as a column in a related list view.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RelatedListField : IParsable
    {
        /// <summary>API name of the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiName { get; set; }
#nullable restore
#else
        public string ApiName { get; set; }
#endif
        /// <summary>Number of decimal places configured for numeric fields.</summary>
        public int? DecimalPlace { get; set; }
        /// <summary>Indicates whether color coding is enabled for this field. Possible values: **true**, **false**.</summary>
        public bool? EnableColourCode { get; set; }
        /// <summary>Display label of the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldLabel { get; set; }
#nullable restore
#else
        public string FieldLabel { get; set; }
#endif
        /// <summary>Formula configuration for the field. Empty object if the field is not a formula field. Returned when include_inner_details contains fields.formula.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldFormula? Formula { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldFormula Formula { get; set; }
#endif
        /// <summary>Unique identifier of the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Lookup configuration for the field. Empty object if the field is not a lookup. Returned when include_inner_details contains fields.lookup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldLookup? Lookup { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldLookup Lookup { get; set; }
#endif
        /// <summary>Masking configuration for the field. Returned when include_inner_details contains fields.mask_details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldMaskDetailsProperty? MaskDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldMaskDetailsProperty MaskDetails { get; set; }
#endif
        /// <summary>List of picklist values for picklist-type fields in the related list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PickListValue>? PickListValues { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.PickListValue> PickListValues { get; set; }
#endif
        /// <summary>Reference field configuration. Returned when include_inner_details contains fields.refer_from_field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldReferFromFieldProperty? ReferFromField { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldReferFromFieldProperty ReferFromField { get; set; }
#endif
        /// <summary>Rollup summary configuration for the field. Empty object if the field is not a rollup summary. Returned when include_inner_details contains fields.rollup_summary.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldRollupSummary? RollupSummary { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldRollupSummary RollupSummary { get; set; }
#endif
        /// <summary>Indicates whether a separator is displayed after this field. Possible values: **true**, **false**.</summary>
        public bool? Separator { get; set; }
        /// <summary>Display order position of the field within the related list.</summary>
        public int? SequenceNumber { get; set; }
        /// <summary>UI type identifier that determines how the field is rendered.</summary>
        public int? UiType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.RelatedListField"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.RelatedListField CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.RelatedListField();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_name", n => { ApiName = n.GetStringValue(); } },
                { "decimal_place", n => { DecimalPlace = n.GetIntValue(); } },
                { "enable_colour_code", n => { EnableColourCode = n.GetBoolValue(); } },
                { "field_label", n => { FieldLabel = n.GetStringValue(); } },
                { "formula", n => { Formula = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldFormula>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldFormula.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lookup", n => { Lookup = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldLookup>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldLookup.CreateFromDiscriminatorValue); } },
                { "mask_details", n => { MaskDetails = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldMaskDetailsProperty>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldMaskDetailsProperty.CreateFromDiscriminatorValue); } },
                { "pick_list_values", n => { PickListValues = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PickListValue>(global::Soenneker.Zoho.OpenApiClient.Models.PickListValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "refer_from_field", n => { ReferFromField = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldReferFromFieldProperty>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldReferFromFieldProperty.CreateFromDiscriminatorValue); } },
                { "rollup_summary", n => { RollupSummary = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldRollupSummary>(global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldRollupSummary.CreateFromDiscriminatorValue); } },
                { "separator", n => { Separator = n.GetBoolValue(); } },
                { "sequence_number", n => { SequenceNumber = n.GetIntValue(); } },
                { "ui_type", n => { UiType = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_name", ApiName);
            writer.WriteIntValue("decimal_place", DecimalPlace);
            writer.WriteBoolValue("enable_colour_code", EnableColourCode);
            writer.WriteStringValue("field_label", FieldLabel);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldFormula>("formula", Formula);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldLookup>("lookup", Lookup);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldMaskDetailsProperty>("mask_details", MaskDetails);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.PickListValue>("pick_list_values", PickListValues);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldReferFromFieldProperty>("refer_from_field", ReferFromField);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.RelatedListFieldRollupSummary>("rollup_summary", RollupSummary);
            writer.WriteBoolValue("separator", Separator);
            writer.WriteIntValue("sequence_number", SequenceNumber);
            writer.WriteIntValue("ui_type", UiType);
        }
    }
}
#pragma warning restore CS0618
