// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents whether a job sheet is required for the service. **Possible values**: Yes, No.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ServicesGetDataNestedJobSheetRequired
    {
        [EnumMember(Value = "Yes")]
        #pragma warning disable CS1591
        Yes,
        #pragma warning restore CS1591
        [EnumMember(Value = "No")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
    }
}
