// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the type of the shared-to entity.Possible values:**territories** - The view is shared with a territory.**roles** - The view is shared with a role.**groups** - The view is shared with a group.**users** - The view is shared with a specific user.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SharedToItemType
    {
        [EnumMember(Value = "territories")]
        #pragma warning disable CS1591
        Territories,
        #pragma warning restore CS1591
        [EnumMember(Value = "roles")]
        #pragma warning disable CS1591
        Roles,
        #pragma warning restore CS1591
        [EnumMember(Value = "groups")]
        #pragma warning disable CS1591
        Groups,
        #pragma warning restore CS1591
        [EnumMember(Value = "users")]
        #pragma warning disable CS1591
        Users,
        #pragma warning restore CS1591
    }
}
