// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>response message</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Share_records_createShareRecords_201_share_message
    {
        [EnumMember(Value = "record will be shared successfully")]
        #pragma warning disable CS1591
        RecordWillBeSharedSuccessfully,
        #pragma warning restore CS1591
    }
}
