// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the action the recipient must perform on the mail merge document.Possible values:**sign** - The recipient must sign the document.**approve** - The recipient must approve the document.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SignersNestedActionType
    {
        [EnumMember(Value = "sign")]
        #pragma warning disable CS1591
        Sign,
        #pragma warning restore CS1591
        [EnumMember(Value = "approve")]
        #pragma warning disable CS1591
        Approve,
        #pragma warning restore CS1591
    }
}
