// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents the request payload for a sign mail merge operation, including the template reference, file name, signing order, and the list of signers.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignMailMergeNested : IParsable
    {
        /// <summary>Represents the name of the file to send for signing or approval.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>Represents the mail merge template reference, identified by the template name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.MailMergeTemplateNested? MailMergeTemplate { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.MailMergeTemplateNested MailMergeTemplate { get; set; }
#endif
        /// <summary>The details of the users you want to sign the document.- recipient_name **string, mandatory** - the name of the user who has to sign or approve the document.- **action_type** string, mandatory - the type of action you want the user to perform. The possible values are sign to **sign** the document, and **approve** to approve the document.- **recipient** JSON object, mandatory    - **value** string, mandatory - the email ID of the user who has to sign or approve the document.&gt; **Note**&gt; The values for the fields **recipient_name** and **recipient.value** will be taken from the mail merge template. If you want to override the values in the template, you must specify the values of these fields in the input body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.SignersNested>? Signers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.SignersNested> Signers { get; set; }
#endif
        /// <summary>Indicates whether recipients must act on the document in a specified sequence.Possible values:**true** - The document first goes for approval, then for signing in the defined order.**false** - Zoho Sign sends the document to all recipients simultaneously.</summary>
        public bool? SignInOrder { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.SignMailMergeNested"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.SignMailMergeNested CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.SignMailMergeNested();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "file_name", n => { FileName = n.GetStringValue(); } },
                { "mail_merge_template", n => { MailMergeTemplate = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.MailMergeTemplateNested>(global::Soenneker.Zoho.OpenApiClient.Models.MailMergeTemplateNested.CreateFromDiscriminatorValue); } },
                { "sign_in_order", n => { SignInOrder = n.GetBoolValue(); } },
                { "signers", n => { Signers = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.SignersNested>(global::Soenneker.Zoho.OpenApiClient.Models.SignersNested.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("file_name", FileName);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.MailMergeTemplateNested>("mail_merge_template", MailMergeTemplate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.SignersNested>("signers", Signers);
            writer.WriteBoolValue("sign_in_order", SignInOrder);
        }
    }
}
#pragma warning restore CS0618
