// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents the request payload to update standard fiscal year settings. When `display_based_on` is set to `end_month`, the `start_month` cannot be `JANUARY`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StandardFiscalYearUpdate : IParsable
    {
        /// <summary>Specify whether the fiscal year label is based on the start month or the end month of the fiscal period. When set to `end_month`, the `start_month` cannot be `JANUARY`. Possible values: `start_month`, `end_month`.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearDisplayBasedOn? DisplayBasedOn { get; set; }
        /// <summary>Specify the start month of the fiscal year. Possible values: `JANUARY`, `FEBRUARY`, `MARCH`, `APRIL`, `MAY`, `JUNE`, `JULY`, `AUGUST`, `SEPTEMBER`, `OCTOBER`, `NOVEMBER`, `DECEMBER`.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearStartMonth? StartMonth { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.StandardFiscalYearUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "display_based_on", n => { DisplayBasedOn = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearDisplayBasedOn>(); } },
                { "start_month", n => { StartMonth = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearStartMonth>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearDisplayBasedOn>("display_based_on", DisplayBasedOn);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.FiscalYearStartMonth>("start_month", StartMonth);
        }
    }
}
#pragma warning restore CS0618
