// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents a single territory record returned by the API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TerritoryGetSchema : IParsable
    {
        /// <summary>Represents the criteria used to auto-assign accounts to the territory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaAccountRuleCriteria? AccountRuleCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaAccountRuleCriteria AccountRuleCriteria { get; set; }
#endif
        /// <summary>Represents the unique API name of the territory used in API requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiName { get; set; }
#nullable restore
#else
        public string ApiName { get; set; }
#endif
        /// <summary>Represents the user who created the territory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaCreatedBy? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaCreatedBy CreatedBy { get; set; }
#endif
        /// <summary>Represents the date and time the territory record took effect, in ISO 8601 format.</summary>
        public DateTimeOffset? CreatedTime { get; set; }
        /// <summary>Represents the criteria used to auto-assign deals to the territory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaDealRuleCriteria? DealRuleCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaDealRuleCriteria DealRuleCriteria { get; set; }
#endif
        /// <summary>Represents the description of the territory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Represents the unique identifier of the territory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Represents the criteria used to auto-assign leads to the territory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaLeadRuleCriteria? LeadRuleCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaLeadRuleCriteria LeadRuleCriteria { get; set; }
#endif
        /// <summary>Represents a territory manager identified by user ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaManager? Manager { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaManager Manager { get; set; }
#endif
        /// <summary>Represents the user who last modified the territory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaModifiedBy? ModifiedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaModifiedBy ModifiedBy { get; set; }
#endif
        /// <summary>Represents the date and time when the territory was last modified, in ISO 8601 format.</summary>
        public DateTimeOffset? ModifiedTime { get; set; }
        /// <summary>Represents the display name of the territory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Represents the access permission for users in this territory. Possible values: **read_write_delete**, **read_only**.</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaPermissionType? PermissionType { get; set; }
        /// <summary>Represents the parent territory to which this territory reports in the hierarchy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaReportingTo? ReportingTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaReportingTo ReportingTo { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_rule_criteria", n => { AccountRuleCriteria = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaAccountRuleCriteria>(global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaAccountRuleCriteria.CreateFromDiscriminatorValue); } },
                { "api_name", n => { ApiName = n.GetStringValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaCreatedBy>(global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaCreatedBy.CreateFromDiscriminatorValue); } },
                { "created_time", n => { CreatedTime = n.GetDateTimeOffsetValue(); } },
                { "deal_rule_criteria", n => { DealRuleCriteria = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaDealRuleCriteria>(global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaDealRuleCriteria.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lead_rule_criteria", n => { LeadRuleCriteria = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaLeadRuleCriteria>(global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaLeadRuleCriteria.CreateFromDiscriminatorValue); } },
                { "manager", n => { Manager = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaManager>(global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaManager.CreateFromDiscriminatorValue); } },
                { "modified_by", n => { ModifiedBy = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaModifiedBy>(global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaModifiedBy.CreateFromDiscriminatorValue); } },
                { "modified_time", n => { ModifiedTime = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "permission_type", n => { PermissionType = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaPermissionType>(); } },
                { "reporting_to", n => { ReportingTo = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaReportingTo>(global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaReportingTo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaAccountRuleCriteria>("account_rule_criteria", AccountRuleCriteria);
            writer.WriteStringValue("api_name", ApiName);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaCreatedBy>("created_by", CreatedBy);
            writer.WriteDateTimeOffsetValue("created_time", CreatedTime);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaDealRuleCriteria>("deal_rule_criteria", DealRuleCriteria);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaLeadRuleCriteria>("lead_rule_criteria", LeadRuleCriteria);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaManager>("manager", Manager);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaModifiedBy>("modified_by", ModifiedBy);
            writer.WriteDateTimeOffsetValue("modified_time", ModifiedTime);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaPermissionType>("permission_type", PermissionType);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.TerritoryGetSchemaReportingTo>("reporting_to", ReportingTo);
        }
    }
}
#pragma warning restore CS0618
