// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Specify the permission type for the territory.Possible values:read_write_delete - Grants full access to the territory, including read, write, and delete operations.read_only - Restricts users to read-only access for the territory.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TerritoriesUpdateTerritoriesRequestTerritoriesItemPermissionType
    {
        [EnumMember(Value = "read_write_delete")]
        #pragma warning disable CS1591
        ReadWriteDelete,
        #pragma warning restore CS1591
        [EnumMember(Value = "read_only")]
        #pragma warning disable CS1591
        ReadOnlyValue,
        #pragma warning restore CS1591
    }
}
