// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the error message describing that the given available days are not within the configured business days.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TheGivenAvailableDaysAreNotThereInBusinessDaysMessage
    {
        [EnumMember(Value = "The given Available Days are not there in business days")]
        #pragma warning disable CS1591
        TheGivenAvailableDaysAreNotThereInBusinessDays,
        #pragma warning restore CS1591
    }
}
