// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the type of action performed on the record. This field is nullable.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimelinesGetTimelines200ResponseTimelineItemAction
    {
        [EnumMember(Value = "converted")]
        #pragma warning disable CS1591
        Converted,
        #pragma warning restore CS1591
        [EnumMember(Value = "score_updated")]
        #pragma warning disable CS1591
        ScoreUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "survey_sent")]
        #pragma warning disable CS1591
        SurveySent,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_notification_sent")]
        #pragma warning disable CS1591
        EmailNotificationSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "consent_mail_sent")]
        #pragma warning disable CS1591
        ConsentMailSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "recommendation_feedback")]
        #pragma warning disable CS1591
        RecommendationFeedback,
        #pragma warning restore CS1591
        [EnumMember(Value = "webhook_invoked")]
        #pragma warning disable CS1591
        WebhookInvoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "function_executed")]
        #pragma warning disable CS1591
        FunctionExecuted,
        #pragma warning restore CS1591
        [EnumMember(Value = "owner_assigned")]
        #pragma warning disable CS1591
        OwnerAssigned,
        #pragma warning restore CS1591
        [EnumMember(Value = "owner_reassigned")]
        #pragma warning disable CS1591
        OwnerReassigned,
        #pragma warning restore CS1591
        [EnumMember(Value = "task_assigned")]
        #pragma warning disable CS1591
        TaskAssigned,
        #pragma warning restore CS1591
        [EnumMember(Value = "create_record")]
        #pragma warning disable CS1591
        CreateRecord,
        #pragma warning restore CS1591
        [EnumMember(Value = "create_connected_record")]
        #pragma warning disable CS1591
        CreateConnectedRecord,
        #pragma warning restore CS1591
        [EnumMember(Value = "transition_executed")]
        #pragma warning disable CS1591
        TransitionExecuted,
        #pragma warning restore CS1591
        [EnumMember(Value = "command_center_log")]
        #pragma warning disable CS1591
        CommandCenterLog,
        #pragma warning restore CS1591
        [EnumMember(Value = "state_change_on_edit")]
        #pragma warning disable CS1591
        StateChangeOnEdit,
        #pragma warning restore CS1591
        [EnumMember(Value = "process_exit_on_edit")]
        #pragma warning disable CS1591
        ProcessExitOnEdit,
        #pragma warning restore CS1591
        [EnumMember(Value = "abrupt_exit")]
        #pragma warning disable CS1591
        AbruptExit,
        #pragma warning restore CS1591
        [EnumMember(Value = "abrupt_exit_api")]
        #pragma warning disable CS1591
        AbruptExitApi,
        #pragma warning restore CS1591
        [EnumMember(Value = "portals_invitation_sent")]
        #pragma warning disable CS1591
        PortalsInvitationSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "portals_invitation_accepted")]
        #pragma warning disable CS1591
        PortalsInvitationAccepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "portals_invitation_resent")]
        #pragma warning disable CS1591
        PortalsInvitationResent,
        #pragma warning restore CS1591
        [EnumMember(Value = "portals_user_type_activated")]
        #pragma warning disable CS1591
        PortalsUserTypeActivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "portals_user_type_deactivated")]
        #pragma warning disable CS1591
        PortalsUserTypeDeactivated,
        #pragma warning restore CS1591
        [EnumMember(Value = "portal_user_transferred")]
        #pragma warning disable CS1591
        PortalUserTransferred,
        #pragma warning restore CS1591
        [EnumMember(Value = "portal_user_deleted")]
        #pragma warning disable CS1591
        PortalUserDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_removed")]
        #pragma warning disable CS1591
        ImageRemoved,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_uploaded")]
        #pragma warning disable CS1591
        ImageUploaded,
        #pragma warning restore CS1591
        [EnumMember(Value = "find_and_merge_duplicate")]
        #pragma warning disable CS1591
        FindAndMergeDuplicate,
        #pragma warning restore CS1591
        [EnumMember(Value = "tag_removed")]
        #pragma warning disable CS1591
        TagRemoved,
        #pragma warning restore CS1591
        [EnumMember(Value = "tag_added")]
        #pragma warning disable CS1591
        TagAdded,
        #pragma warning restore CS1591
        [EnumMember(Value = "tags_overwritten")]
        #pragma warning disable CS1591
        TagsOverwritten,
        #pragma warning restore CS1591
        [EnumMember(Value = "submitted_for_review")]
        #pragma warning disable CS1591
        SubmittedForReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "resubmitted_for_review")]
        #pragma warning disable CS1591
        ResubmittedForReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "reviewed")]
        #pragma warning disable CS1591
        Reviewed,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejected_in_review")]
        #pragma warning disable CS1591
        RejectedInReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "reviewed_during_resubmit")]
        #pragma warning disable CS1591
        ReviewedDuringResubmit,
        #pragma warning restore CS1591
        [EnumMember(Value = "entered_in_system")]
        #pragma warning disable CS1591
        EnteredInSystem,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated")]
        #pragma warning disable CS1591
        Updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "webinar_invitation_sent")]
        #pragma warning disable CS1591
        WebinarInvitationSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "backstage_invitation_sent")]
        #pragma warning disable CS1591
        BackstageInvitationSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment_to_post")]
        #pragma warning disable CS1591
        CommentToPost,
        #pragma warning restore CS1591
        [EnumMember(Value = "reply_to_message")]
        #pragma warning disable CS1591
        ReplyToMessage,
        #pragma warning restore CS1591
        [EnumMember(Value = "reply_to_comment")]
        #pragma warning disable CS1591
        ReplyToComment,
        #pragma warning restore CS1591
        [EnumMember(Value = "like_to_comment")]
        #pragma warning disable CS1591
        LikeToComment,
        #pragma warning restore CS1591
        [EnumMember(Value = "retweet")]
        #pragma warning disable CS1591
        Retweet,
        #pragma warning restore CS1591
        [EnumMember(Value = "reply_to_tweet")]
        #pragma warning disable CS1591
        ReplyToTweet,
        #pragma warning restore CS1591
        [EnumMember(Value = "process_entry")]
        #pragma warning disable CS1591
        ProcessEntry,
        #pragma warning restore CS1591
        [EnumMember(Value = "process_exit")]
        #pragma warning disable CS1591
        ProcessExit,
        #pragma warning restore CS1591
        [EnumMember(Value = "escalation_mail")]
        #pragma warning disable CS1591
        EscalationMail,
        #pragma warning restore CS1591
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "click")]
        #pragma warning disable CS1591
        Click,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounce")]
        #pragma warning disable CS1591
        Bounce,
        #pragma warning restore CS1591
        [EnumMember(Value = "received")]
        #pragma warning disable CS1591
        Received,
        #pragma warning restore CS1591
        [EnumMember(Value = "missed")]
        #pragma warning disable CS1591
        Missed,
        #pragma warning restore CS1591
        [EnumMember(Value = "added")]
        #pragma warning disable CS1591
        Added,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_approved")]
        #pragma warning disable CS1591
        ImageApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_approval")]
        #pragma warning disable CS1591
        ImageApproval,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejection_mail_sent")]
        #pragma warning disable CS1591
        RejectionMailSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "final_approval_mail_copy_sent")]
        #pragma warning disable CS1591
        FinalApprovalMailCopySent,
        #pragma warning restore CS1591
        [EnumMember(Value = "automatic_transition")]
        #pragma warning disable CS1591
        AutomaticTransition,
        #pragma warning restore CS1591
        [EnumMember(Value = "record_exit_on_edit")]
        #pragma warning disable CS1591
        RecordExitOnEdit,
        #pragma warning restore CS1591
        [EnumMember(Value = "state_executed")]
        #pragma warning disable CS1591
        StateExecuted,
        #pragma warning restore CS1591
        [EnumMember(Value = "automatic_transition_action")]
        #pragma warning disable CS1591
        AutomaticTransitionAction,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_signature")]
        #pragma warning disable CS1591
        UserSignature,
        #pragma warning restore CS1591
        [EnumMember(Value = "Message_template_sent")]
        #pragma warning disable CS1591
        MessageTemplateSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "action_executed")]
        #pragma warning disable CS1591
        ActionExecuted,
        #pragma warning restore CS1591
        [EnumMember(Value = "mass_association")]
        #pragma warning disable CS1591
        MassAssociation,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "restored")]
        #pragma warning disable CS1591
        Restored,
        #pragma warning restore CS1591
        [EnumMember(Value = "subform_automation_trigger")]
        #pragma warning disable CS1591
        SubformAutomationTrigger,
        #pragma warning restore CS1591
    }
}
