// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Field name to unblock</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UnblockEmailUnblockEmailById_unblock_fields
    {
        [EnumMember(Value = "Email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
    }
}
