// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Indicates the outcome of the deletion request.Possible values:User deleted - The user was removed from the organization successfully.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserDeletedMessage
    {
        [EnumMember(Value = "User deleted")]
        #pragma warning disable CS1591
        UserDeleted,
        #pragma warning restore CS1591
    }
}
