// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>sort order preference</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserDetails_sort_order_preference__s
    {
        [EnumMember(Value = "First Name,Last Name")]
        #pragma warning disable CS1591
        FirstNameLastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "Last Name,First Name")]
        #pragma warning disable CS1591
        LastNameFirstName,
        #pragma warning restore CS1591
    }
}
