// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper"/>, <see cref="global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper_2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserDetailsStatus : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper? UserDetailsStatusWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper UserDetailsStatusWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper_2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper_2? UserDetailsStatusWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper_2 UserDetailsStatusWrapper2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus();
            if("UserDetailsStatus_Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserDetailsStatusWrapper = new global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper();
            }
            else if("UserDetailsStatus_Wrapper_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserDetailsStatusWrapper2 = new global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper_2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UserDetailsStatusWrapper != null)
            {
                return UserDetailsStatusWrapper.GetFieldDeserializers();
            }
            else if(UserDetailsStatusWrapper2 != null)
            {
                return UserDetailsStatusWrapper2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UserDetailsStatusWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper>(null, UserDetailsStatusWrapper);
            }
            else if(UserDetailsStatusWrapper2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.UserDetailsStatus_Wrapper_2>(null, UserDetailsStatusWrapper2);
            }
        }
    }
}
#pragma warning restore CS0618
