// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the error code for the update failure. Possible values:**INVALID_DATA** - One or more field values in the request body are invalid.**MANDATORY_NOT_FOUND** - A required field is missing from the request body.**DUPLICATE_DATA** - A user group with the same name already exists.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserGroupsUpdateGroup400ResponseUserGroupsItemCode
    {
        [EnumMember(Value = "INVALID_DATA")]
        #pragma warning disable CS1591
        InvalidData,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANDATORY_NOT_FOUND")]
        #pragma warning disable CS1591
        MandatoryNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "DUPLICATE_DATA")]
        #pragma warning disable CS1591
        DuplicateData,
        #pragma warning restore CS1591
    }
}
