// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents a variable to create, including api_name, name, optional description, data type (text, integer, boolean, date, float), initial value, and the target variable_group reference.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VariableCreationItem : IParsable
    {
        /// <summary>this shows the api name of the variables (Required)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiName { get; set; }
#nullable restore
#else
        public string ApiName { get; set; }
#endif
        /// <summary>description of the variables</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>It shows name of the variables (Required)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Type of the variables (Required)</summary>
        public global::Soenneker.Zoho.OpenApiClient.Models.VariableCreationItem_type? Type { get; set; }
        /// <summary>Initial value of variable</summary>
        public int? Value { get; set; }
        /// <summary>Nested object that identifies the variable group when defining a variable. Includes the group&apos;s id (required) and rid (UUID) if available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.VariableGroupIdentifierInput? VariableGroup { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.VariableGroupIdentifierInput VariableGroup { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.VariableCreationItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.VariableCreationItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.VariableCreationItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_name", n => { ApiName = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.VariableCreationItem_type>(); } },
                { "value", n => { Value = n.GetIntValue(); } },
                { "variable_group", n => { VariableGroup = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.VariableGroupIdentifierInput>(global::Soenneker.Zoho.OpenApiClient.Models.VariableGroupIdentifierInput.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_name", ApiName);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Zoho.OpenApiClient.Models.VariableCreationItem_type>("type", Type);
            writer.WriteIntValue("value", Value);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.VariableGroupIdentifierInput>("variable_group", VariableGroup);
        }
    }
}
#pragma warning restore CS0618
