// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Nested schema for webhook_failures
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Webhooks_GeneratedSchema3 : IParsable
    {
        /// <summary>Nested schema for entity_details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema12? EntityDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema12 EntityDetails { get; set; }
#endif
        /// <summary>&quot;Field: failure_reason&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureReason { get; set; }
#nullable restore
#else
        public string FailureReason { get; set; }
#endif
        /// <summary>&quot;Field: failure_time&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureTime { get; set; }
#nullable restore
#else
        public string FailureTime { get; set; }
#endif
        /// <summary>&quot;Field: id&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Nested schema for webhook</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.GeneratedSchema11? Webhook { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.GeneratedSchema11 Webhook { get; set; }
#endif
        /// <summary>Nested schema for workflow_rule</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema8? WorkflowRule { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema8 WorkflowRule { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entity_details", n => { EntityDetails = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema12>(global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema12.CreateFromDiscriminatorValue); } },
                { "failure_reason", n => { FailureReason = n.GetStringValue(); } },
                { "failure_time", n => { FailureTime = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "webhook", n => { Webhook = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.GeneratedSchema11>(global::Soenneker.Zoho.OpenApiClient.Models.GeneratedSchema11.CreateFromDiscriminatorValue); } },
                { "workflow_rule", n => { WorkflowRule = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema8>(global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema8.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema12>("entity_details", EntityDetails);
            writer.WriteStringValue("failure_reason", FailureReason);
            writer.WriteStringValue("failure_time", FailureTime);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.GeneratedSchema11>("webhook", Webhook);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.Webhooks_GeneratedSchema8>("workflow_rule", WorkflowRule);
        }
    }
}
#pragma warning restore CS0618
