// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the error message describing that the Unavailable From date must be greater than the current date when the service status is available.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WhenTheServiceStatusIsAvailableCommaUnavailableFromMustBeGreaterThanCurrentDateMessage
    {
        [EnumMember(Value = "When the service status is available, Unavailable From must be greater than current date")]
        #pragma warning disable CS1591
        WhenTheServiceStatusIsAvailableCommaUnavailableFromMustBeGreaterThanCurrentDate,
        #pragma warning restore CS1591
    }
}
