// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents an action type available for the module. Defines an operation that can be performed when a workflow rule triggers. The limit field is the per-type cap that applies independently to instant_actions and scheduled_actions - for instance, if limit=5, you can add up to 5 instances in instant_actions and up to 5 in scheduled_actions of the same rule.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowConfigurationsAction : IParsable
    {
        /// <summary>Represents the API identifier of the action type used when creating or modifying workflow rules (for example, field_updates, email_notifications, webhooks, assign_owner, add_tags, remove_tags, create_record, add_meeting, schedule_call, convert, functions, flow).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiName { get; set; }
#nullable restore
#else
        public string ApiName { get; set; }
#endif
        /// <summary>Indicates whether this action type is an associate action. Associate actions link or associate records between modules (for example, linking a Contact to a Deal or associating a Product with an Order). Associate actions differ from standard data-write actions such as field_updates or email_notifications.Possible values: **true** - This action type is an associate action. **false** - This action type is a standard non-associate action.</summary>
        public bool? AssociateAction { get; set; }
        /// <summary>Indicates whether this action type can be edited directly from the workflow configuration UI page. Not relevant for API usage.</summary>
        public bool? IsClickable { get; set; }
        /// <summary>Maximum number of instances of this action type allowed per workflow rule. Applies independently to instant_actions and scheduled_actions - for instance, if limit=5, you can add up to 5 instances in instant_actions and up to 5 in scheduled_actions. Returns LIMIT_EXCEEDED if exceeded.</summary>
        public int? Limit { get; set; }
        /// <summary>Represents the maximum number of items within a single action instance. For example, add_tags and remove_tags allow a maximum of 10 tags per action. Returns null if no per-action item limit applies.</summary>
        public int? LimitPerAction { get; set; }
        /// <summary>Represents the display name of the action type as shown in the CRM UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Indicates whether this action type can be used as a scheduled (time-delayed) action in a workflow rule. **Possible values:** true - This action type is supported in scheduled_actions (for example, time-delayed email_notifications or field_updates). false - This action type is only supported in instant_actions.</summary>
        public bool? SupportedInScheduledAction { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.WorkflowConfigurationsAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.WorkflowConfigurationsAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.WorkflowConfigurationsAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_name", n => { ApiName = n.GetStringValue(); } },
                { "associate_action", n => { AssociateAction = n.GetBoolValue(); } },
                { "is_clickable", n => { IsClickable = n.GetBoolValue(); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "limit_per_action", n => { LimitPerAction = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "supported_in_scheduled_action", n => { SupportedInScheduledAction = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_name", ApiName);
            writer.WriteBoolValue("associate_action", AssociateAction);
            writer.WriteBoolValue("is_clickable", IsClickable);
            writer.WriteIntValue("limit", Limit);
            writer.WriteIntValue("limit_per_action", LimitPerAction);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("supported_in_scheduled_action", SupportedInScheduledAction);
        }
    }
}
#pragma warning restore CS0618
