// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Error code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Workflow_tasks_ErrorResponseCore18_code
    {
        [EnumMember(Value = "AUTHORIZATION_ERROR")]
        #pragma warning disable CS1591
        AUTHORIZATION_ERROR,
        #pragma warning restore CS1591
    }
}
