// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>
    /// Represents the configuration object for updating an existing workflow rule, including the rule ID and optional fields such as name, trigger, conditions, and lock status.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowRulePutNestedSchema : IParsable
    {
        /// <summary>Specify the array of condition objects to update. On update, unspecified conditions are preserved. Conditions with a null ID are added; conditions with an existing ID get replaced; conditions with a **_delete** flag are removed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zoho.OpenApiClient.Models.ConditionsNestedSchema>? Conditions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zoho.OpenApiClient.Models.ConditionsNestedSchema> Conditions { get; set; }
#endif
        /// <summary>Specify the workflow rule description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Represents the trigger configuration that defines when the workflow rule fires, including the trigger type and its associated details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenNestedSchema? ExecuteWhen { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenNestedSchema ExecuteWhen { get; set; }
#endif
        /// <summary>Represents the unique ID of the workflow rule to update. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Specify whether the workflow rule should be locked to prevent editing by other users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaLock? Lock { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaLock Lock { get; set; }
#endif
        /// <summary>Represents a CRM module or field reference using its API name and unique numeric ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.ModuleOrFieldNestedSchema? Module { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.ModuleOrFieldNestedSchema Module { get; set; }
#endif
        /// <summary>Specify the workflow rule name. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Specify the activation state of the workflow rule. When setting **active** to false, you can optionally delete all associated scheduled actions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaStatus? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaStatus Status { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conditions", n => { Conditions = n.GetCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.ConditionsNestedSchema>(global::Soenneker.Zoho.OpenApiClient.Models.ConditionsNestedSchema.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "execute_when", n => { ExecuteWhen = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenNestedSchema>(global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenNestedSchema.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lock", n => { Lock = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaLock>(global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaLock.CreateFromDiscriminatorValue); } },
                { "module", n => { Module = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ModuleOrFieldNestedSchema>(global::Soenneker.Zoho.OpenApiClient.Models.ModuleOrFieldNestedSchema.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaStatus>(global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaStatus.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zoho.OpenApiClient.Models.ConditionsNestedSchema>("conditions", Conditions);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ExecuteWhenNestedSchema>("execute_when", ExecuteWhen);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaLock>("lock", Lock);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.ModuleOrFieldNestedSchema>("module", Module);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Zoho.OpenApiClient.Models.WorkflowRulePutNestedSchemaStatus>("status", Status);
        }
    }
}
#pragma warning restore CS0618
