// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Represents the comparison operator applied to the filter criterion. **${ANYVALUE}** is a special value supported only in field update triggers; it matches any change to the monitored field value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowSimpleFilterCriterionComparator
    {
        [EnumMember(Value = "equal")]
        #pragma warning disable CS1591
        Equal,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_equal")]
        #pragma warning disable CS1591
        NotEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "like")]
        #pragma warning disable CS1591
        Like,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_like")]
        #pragma warning disable CS1591
        NotLike,
        #pragma warning restore CS1591
        [EnumMember(Value = "starts_with")]
        #pragma warning disable CS1591
        StartsWith,
        #pragma warning restore CS1591
        [EnumMember(Value = "ends_with")]
        #pragma warning disable CS1591
        EndsWith,
        #pragma warning restore CS1591
        [EnumMember(Value = "contains")]
        #pragma warning disable CS1591
        Contains,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_contains")]
        #pragma warning disable CS1591
        NotContains,
        #pragma warning restore CS1591
        [EnumMember(Value = "greater_than")]
        #pragma warning disable CS1591
        GreaterThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "greater_equal")]
        #pragma warning disable CS1591
        GreaterEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "less_equal")]
        #pragma warning disable CS1591
        LessEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "less_than")]
        #pragma warning disable CS1591
        LessThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "in")]
        #pragma warning disable CS1591
        InValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_in")]
        #pragma warning disable CS1591
        NotIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "between")]
        #pragma warning disable CS1591
        Between,
        #pragma warning restore CS1591
        [EnumMember(Value = "${ANYVALUE}")]
        #pragma warning disable CS1591
        DollarLeftBraceANYVALUERightBrace,
        #pragma warning restore CS1591
    }
}
