// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Error message</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Workflow_tasks_ErrorResponseCore14_message
    {
        [EnumMember(Value = "Required field is missing")]
        #pragma warning disable CS1591
        RequiredFieldIsMissing,
        #pragma warning restore CS1591
    }
}
