// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Indicates the value resolution mode of the criterion, distinguishing whether the filter value is a literal value, a merge field reference, a predefined system variable, or another field reference.Possible values:value - The value is a direct literal.merge_field - The value is a merge field reference.pre_defined - The value is a predefined system variable placeholder.field - The value references another field.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowRulesTextFilterCriterionRequestType
    {
        [EnumMember(Value = "merge_field")]
        #pragma warning disable CS1591
        MergeField,
        #pragma warning restore CS1591
        [EnumMember(Value = "pre_defined")]
        #pragma warning disable CS1591
        PreDefined,
        #pragma warning restore CS1591
        [EnumMember(Value = "value")]
        #pragma warning disable CS1591
        Value,
        #pragma warning restore CS1591
        [EnumMember(Value = "field")]
        #pragma warning disable CS1591
        Field,
        #pragma warning restore CS1591
    }
}
