// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zoho.OpenApiClient.Models
{
    /// <summary>Error code identifying the type of validation failure.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ZiaEnrichmentUpdateZiaEnrichmentConfigurations400ResponseDataEnrichmentItemCode
    {
        [EnumMember(Value = "INVALID_DATA")]
        #pragma warning disable CS1591
        InvalidData,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANDATORY_NOT_FOUND")]
        #pragma warning disable CS1591
        MandatoryNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_ALLOWED")]
        #pragma warning disable CS1591
        NotAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_SUPPORTED")]
        #pragma warning disable CS1591
        NotSupported,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_MAPPING")]
        #pragma warning disable CS1591
        InvalidMapping,
        #pragma warning restore CS1591
    }
}
