// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Layouts_activate_deactivate.Settings.Layouts.Item.Actions.Activate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zoho.OpenApiClient.Layouts_activate_deactivate.Settings.Layouts.Item.Actions
{
    /// <summary>
    /// Builds and executes requests for operations under \layouts_activate_deactivate\settings\layouts\{id}\actions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activate property</summary>
        public global::Soenneker.Zoho.OpenApiClient.Layouts_activate_deactivate.Settings.Layouts.Item.Actions.Activate.ActivateRequestBuilder Activate
        {
            get => new global::Soenneker.Zoho.OpenApiClient.Layouts_activate_deactivate.Settings.Layouts.Item.Actions.Activate.ActivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Layouts_activate_deactivate.Settings.Layouts.Item.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/layouts_activate_deactivate/settings/layouts/{id}/actions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Layouts_activate_deactivate.Settings.Layouts.Item.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/layouts_activate_deactivate/settings/layouts/{id}/actions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
