// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts
{
    /// <summary>
    /// Builds and executes requests for operations under \map_dependency\settings\layouts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LayoutsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Zoho.OpenApiClient.map_dependency.settings.layouts.item collection</summary>
        /// <param name="position">The unique identifier of the layout</param>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item.WithLayoutItemRequestBuilder"/></returns>
        public global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item.WithLayoutItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("layoutId", position);
                return new global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.Item.WithLayoutItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.LayoutsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LayoutsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/map_dependency/settings/layouts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Map_dependency.Settings.Layouts.LayoutsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LayoutsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/map_dependency/settings/layouts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
