// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Conversion_option.Leads.Item.Conversion_options;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zoho.OpenApiClient.Conversion_option.Leads.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \conversion_option\Leads\{leadId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLeadItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The conversion_options property</summary>
        public global::Soenneker.Zoho.OpenApiClient.Conversion_option.Leads.Item.Conversion_options.Conversion_optionsRequestBuilder Conversion_options
        {
            get => new global::Soenneker.Zoho.OpenApiClient.Conversion_option.Leads.Item.Conversion_options.Conversion_optionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Conversion_option.Leads.Item.WithLeadItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLeadItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/conversion_option/Leads/{leadId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Conversion_option.Leads.Item.WithLeadItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLeadItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/conversion_option/Leads/{leadId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
