// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zoho.OpenApiClient.Email_drafts.Item.Item.Email_drafts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \email_drafts\{module}\{record}\__email_drafts\{draft}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDraftItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Email_drafts.Item.Item.Email_drafts.Item.WithDraftItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDraftItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/email_drafts/{module}/{record}/__email_drafts/{draft}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Email_drafts.Item.Item.Email_drafts.Item.WithDraftItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDraftItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/email_drafts/{module}/{record}/__email_drafts/{draft}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes the specified email draft for the given record.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsDeleteEmailDrafts200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsDeleteEmailDrafts400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Zoho.OpenApiClient.Models.NoPermissionForbiddenResponse">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsDeleteEmailDrafts200Response?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsDeleteEmailDrafts200Response> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsDeleteEmailDrafts400Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Zoho.OpenApiClient.Models.NoPermissionForbiddenResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsDeleteEmailDrafts200Response>(requestInfo, global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsDeleteEmailDrafts200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the specified email draft for the given record in the module.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsGetEmailDraft200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsGetEmailDraft400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Zoho.OpenApiClient.Models.NoPermissionForbiddenResponse">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsGetEmailDraft200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsGetEmailDraft200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsGetEmailDraft400Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Zoho.OpenApiClient.Models.NoPermissionForbiddenResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsGetEmailDraft200Response>(requestInfo, global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsGetEmailDraft200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the specified email draft for the given record in the module.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDrafts200Response"/></returns>
        /// <param name="body">Request body for updating a single email draft.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDrafts400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Zoho.OpenApiClient.Models.NoPermissionForbiddenResponse">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDrafts200Response?> PutAsync(global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDraftsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDrafts200Response> PutAsync(global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDraftsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDrafts400Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Zoho.OpenApiClient.Models.NoPermissionForbiddenResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDrafts200Response>(requestInfo, global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDrafts200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes the specified email draft for the given record.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves the specified email draft for the given record in the module.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates the specified email draft for the given record in the module.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for updating a single email draft.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDraftsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Zoho.OpenApiClient.Models.EmailDraftsUpdateEmailDraftsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Email_drafts.Item.Item.Email_drafts.Item.WithDraftItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zoho.OpenApiClient.Email_drafts.Item.Item.Email_drafts.Item.WithDraftItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zoho.OpenApiClient.Email_drafts.Item.Item.Email_drafts.Item.WithDraftItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
