// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zoho.OpenApiClient.Related_records.Item.Deleted.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zoho.OpenApiClient.Related_records.Item.Deleted.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \related_records\{parentRecordModule}\deleted\{parentRecord}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithParentRecordItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Zoho.OpenApiClient.related_records.item.deleted.item.item collection</summary>
        /// <param name="position">The name of the related list (module) containing the records to retrieve or modify</param>
        /// <returns>A <see cref="global::Soenneker.Zoho.OpenApiClient.Related_records.Item.Deleted.Item.Item.WithRelatedListItemRequestBuilder"/></returns>
        public global::Soenneker.Zoho.OpenApiClient.Related_records.Item.Deleted.Item.Item.WithRelatedListItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("relatedList", position);
                return new global::Soenneker.Zoho.OpenApiClient.Related_records.Item.Deleted.Item.Item.WithRelatedListItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Related_records.Item.Deleted.Item.WithParentRecordItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithParentRecordItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/related_records/{parentRecordModule}/deleted/{parentRecord}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zoho.OpenApiClient.Related_records.Item.Deleted.Item.WithParentRecordItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithParentRecordItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/related_records/{parentRecordModule}/deleted/{parentRecord}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
